// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnalyticsEvidenceSummary = `-- name: GetAnalyticsEvidenceSummary :one
WITH scoped_cases AS (
    SELECT c.id
    FROM ops.case_records c
    WHERE ($1::timestamptz IS NULL OR c.created_at >= $1::timestamptz)
      AND c.created_at < $2::timestamptz
),
case_evidence AS (
    SELECT
        sc.id AS case_id,
        COUNT(e.id)::int AS evidence_count,
        COUNT(e.id) FILTER (WHERE e.evidence_status = 'confirmed')::int AS confirmed_count
    FROM scoped_cases sc
    LEFT JOIN ops.case_evidence_items e ON e.case_id = sc.id
        AND e.created_at < $2::timestamptz
    GROUP BY sc.id
)
SELECT
    COALESCE((
        SELECT COUNT(*)
        FROM ops.case_evidence_items e
        WHERE ($1::timestamptz IS NULL OR e.created_at >= $1::timestamptz)
          AND e.created_at < $2::timestamptz
    ), 0)::int AS total_items,
    COUNT(*) FILTER (WHERE evidence_count = 0)::int AS cases_without_evidence,
    COUNT(*) FILTER (WHERE confirmed_count = 0)::int AS cases_without_confirmed_evidence
FROM case_evidence
`

type GetAnalyticsEvidenceSummaryParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type GetAnalyticsEvidenceSummaryRow struct {
	TotalItems                    int32 `json:"total_items"`
	CasesWithoutEvidence          int32 `json:"cases_without_evidence"`
	CasesWithoutConfirmedEvidence int32 `json:"cases_without_confirmed_evidence"`
}

func (q *Queries) GetAnalyticsEvidenceSummary(ctx context.Context, arg GetAnalyticsEvidenceSummaryParams) (GetAnalyticsEvidenceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAnalyticsEvidenceSummary, arg.FromAt, arg.ToAt)
	var i GetAnalyticsEvidenceSummaryRow
	err := row.Scan(&i.TotalItems, &i.CasesWithoutEvidence, &i.CasesWithoutConfirmedEvidence)
	return i, err
}

const getAnalyticsOperatingSummary = `-- name: GetAnalyticsOperatingSummary :one
WITH scoped_matters AS (
    SELECT c.id AS case_id, ml.submitted_at, ml.customer_status, c.status, c.resolved_at
    FROM pilot.matter_links ml
    JOIN ops.case_records c ON c.id = ml.case_id
    WHERE ($2::timestamptz IS NULL OR ml.submitted_at >= $2::timestamptz)
      AND ml.submitted_at < $1::timestamptz
),
current_decisions AS (
    SELECT d.decision_source
    FROM ops.case_decisions d
    JOIN scoped_matters sm ON sm.case_id = d.case_id
    WHERE d.status = 'current'
      AND d.created_at < $1::timestamptz
)
SELECT
    COUNT(*)::int AS submitted_count,
    COUNT(*) FILTER (WHERE customer_status = 'resolved')::int AS resolved_count,
    COUNT(*) FILTER (WHERE customer_status = 'in_review')::int AS in_review_count,
    COUNT(*) FILTER (WHERE customer_status = 'reopened')::int AS reopened_count,
    COUNT(*) FILTER (WHERE status = 'closed_unresolved')::int AS unresolved_count,
    COALESCE(AVG(EXTRACT(EPOCH FROM (resolved_at - submitted_at))) FILTER (WHERE resolved_at IS NOT NULL), 0)::int AS average_seconds_to_resolve,
    COALESCE(MAX(EXTRACT(EPOCH FROM ($1::timestamptz - submitted_at))) FILTER (WHERE customer_status = 'in_review'), 0)::int AS oldest_in_review_seconds,
    (SELECT COUNT(*) FROM current_decisions WHERE decision_source = 'accepted_proposal')::int AS accepted_proposal_count,
    (SELECT COUNT(*) FROM current_decisions WHERE decision_source = 'manual_override')::int AS manual_override_count
FROM scoped_matters
`

type GetAnalyticsOperatingSummaryParams struct {
	ToAt   pgtype.Timestamptz `json:"to_at"`
	FromAt pgtype.Timestamptz `json:"from_at"`
}

type GetAnalyticsOperatingSummaryRow struct {
	SubmittedCount          int32 `json:"submitted_count"`
	ResolvedCount           int32 `json:"resolved_count"`
	InReviewCount           int32 `json:"in_review_count"`
	ReopenedCount           int32 `json:"reopened_count"`
	UnresolvedCount         int32 `json:"unresolved_count"`
	AverageSecondsToResolve int32 `json:"average_seconds_to_resolve"`
	OldestInReviewSeconds   int32 `json:"oldest_in_review_seconds"`
	AcceptedProposalCount   int32 `json:"accepted_proposal_count"`
	ManualOverrideCount     int32 `json:"manual_override_count"`
}

func (q *Queries) GetAnalyticsOperatingSummary(ctx context.Context, arg GetAnalyticsOperatingSummaryParams) (GetAnalyticsOperatingSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAnalyticsOperatingSummary, arg.ToAt, arg.FromAt)
	var i GetAnalyticsOperatingSummaryRow
	err := row.Scan(
		&i.SubmittedCount,
		&i.ResolvedCount,
		&i.InReviewCount,
		&i.ReopenedCount,
		&i.UnresolvedCount,
		&i.AverageSecondsToResolve,
		&i.OldestInReviewSeconds,
		&i.AcceptedProposalCount,
		&i.ManualOverrideCount,
	)
	return i, err
}

const getAnalyticsSourceHealth = `-- name: GetAnalyticsSourceHealth :one
WITH latest_run AS (
    SELECT id, status
    FROM ops.runs
    ORDER BY created_at DESC
    LIMIT 1
),
latest_success AS (
    SELECT finished_at
    FROM ops.runs
    WHERE status = 'completed'
    ORDER BY finished_at DESC NULLS LAST, created_at DESC
    LIMIT 1
),
latest_error AS (
    SELECT j.error_message
    FROM ops.jobs j
    JOIN latest_run lr ON lr.id = j.run_id
    WHERE j.error_message IS NOT NULL AND j.error_message <> ''
    ORDER BY j.updated_at DESC
    LIMIT 1
)
SELECT
    COALESCE(lr.id::text, '')::text AS latest_run_id,
    COALESCE(lr.status, 'none')::text AS latest_run_status,
    COALESCE(le.error_message, '')::text AS latest_error,
    COALESCE((
        SELECT COUNT(*)
        FROM ops.jobs j
        JOIN latest_run latest ON latest.id = j.run_id
        WHERE j.status = 'failed'
    ), 0)::int AS failed_job_count,
    COALESCE((
        SELECT COUNT(*)
        FROM ops.jobs j
        JOIN latest_run latest ON latest.id = j.run_id
        WHERE j.status IN ('pending', 'leased', 'running')
    ), 0)::int AS pending_job_count,
    (SELECT COUNT(*) FROM stage.quarantined_records)::int AS quarantined_record_count,
    (SELECT COUNT(*) FROM core.source_links)::int AS source_link_count,
    ls.finished_at AS last_successful_run_at
FROM (SELECT 1) anchor
LEFT JOIN latest_run lr ON TRUE
LEFT JOIN latest_success ls ON TRUE
LEFT JOIN latest_error le ON TRUE
`

type GetAnalyticsSourceHealthRow struct {
	LatestRunID            string             `json:"latest_run_id"`
	LatestRunStatus        string             `json:"latest_run_status"`
	LatestError            string             `json:"latest_error"`
	FailedJobCount         int32              `json:"failed_job_count"`
	PendingJobCount        int32              `json:"pending_job_count"`
	QuarantinedRecordCount int32              `json:"quarantined_record_count"`
	SourceLinkCount        int32              `json:"source_link_count"`
	LastSuccessfulRunAt    pgtype.Timestamptz `json:"last_successful_run_at"`
}

func (q *Queries) GetAnalyticsSourceHealth(ctx context.Context) (GetAnalyticsSourceHealthRow, error) {
	row := q.db.QueryRow(ctx, getAnalyticsSourceHealth)
	var i GetAnalyticsSourceHealthRow
	err := row.Scan(
		&i.LatestRunID,
		&i.LatestRunStatus,
		&i.LatestError,
		&i.FailedJobCount,
		&i.PendingJobCount,
		&i.QuarantinedRecordCount,
		&i.SourceLinkCount,
		&i.LastSuccessfulRunAt,
	)
	return i, err
}

const listAnalyticsDecisionMix = `-- name: ListAnalyticsDecisionMix :many
SELECT
    d.decision,
    COUNT(*)::int AS count,
    COUNT(*) FILTER (WHERE d.decision_source = 'manual')::int AS manual_count,
    COUNT(*) FILTER (WHERE d.decision_source = 'manual_override')::int AS manual_override_count,
    COUNT(*) FILTER (WHERE d.decision_source = 'accepted_proposal')::int AS accepted_proposal_count
FROM ops.case_decisions d
WHERE d.status = 'current'
  AND ($1::timestamptz IS NULL OR d.created_at >= $1::timestamptz)
  AND d.created_at < $2::timestamptz
GROUP BY d.decision
ORDER BY count DESC, d.decision ASC
`

type ListAnalyticsDecisionMixParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type ListAnalyticsDecisionMixRow struct {
	Decision              string `json:"decision"`
	Count                 int32  `json:"count"`
	ManualCount           int32  `json:"manual_count"`
	ManualOverrideCount   int32  `json:"manual_override_count"`
	AcceptedProposalCount int32  `json:"accepted_proposal_count"`
}

func (q *Queries) ListAnalyticsDecisionMix(ctx context.Context, arg ListAnalyticsDecisionMixParams) ([]ListAnalyticsDecisionMixRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsDecisionMix, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalyticsDecisionMixRow
	for rows.Next() {
		var i ListAnalyticsDecisionMixRow
		if err := rows.Scan(
			&i.Decision,
			&i.Count,
			&i.ManualCount,
			&i.ManualOverrideCount,
			&i.AcceptedProposalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsEvidenceSourceTypeMix = `-- name: ListAnalyticsEvidenceSourceTypeMix :many
SELECT source_type, COUNT(*)::int AS count
FROM ops.case_evidence_items
WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
  AND created_at < $2::timestamptz
GROUP BY source_type
ORDER BY count DESC, source_type ASC
`

type ListAnalyticsEvidenceSourceTypeMixParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type ListAnalyticsEvidenceSourceTypeMixRow struct {
	SourceType string `json:"source_type"`
	Count      int32  `json:"count"`
}

func (q *Queries) ListAnalyticsEvidenceSourceTypeMix(ctx context.Context, arg ListAnalyticsEvidenceSourceTypeMixParams) ([]ListAnalyticsEvidenceSourceTypeMixRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsEvidenceSourceTypeMix, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalyticsEvidenceSourceTypeMixRow
	for rows.Next() {
		var i ListAnalyticsEvidenceSourceTypeMixRow
		if err := rows.Scan(&i.SourceType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsEvidenceStatusMix = `-- name: ListAnalyticsEvidenceStatusMix :many
SELECT evidence_status AS status, COUNT(*)::int AS count
FROM ops.case_evidence_items
WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
  AND created_at < $2::timestamptz
GROUP BY evidence_status
ORDER BY count DESC, evidence_status ASC
`

type ListAnalyticsEvidenceStatusMixParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type ListAnalyticsEvidenceStatusMixRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) ListAnalyticsEvidenceStatusMix(ctx context.Context, arg ListAnalyticsEvidenceStatusMixParams) ([]ListAnalyticsEvidenceStatusMixRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsEvidenceStatusMix, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalyticsEvidenceStatusMixRow
	for rows.Next() {
		var i ListAnalyticsEvidenceStatusMixRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsReasonCodes = `-- name: ListAnalyticsReasonCodes :many
SELECT
    rc.code,
    rc.label,
    rc.category,
    COUNT(*)::int AS count
FROM ops.case_decisions d
JOIN ops.case_decision_reason_codes drc ON drc.decision_id = d.id
JOIN ops.reason_codes rc ON rc.code = drc.reason_code
WHERE d.status = 'current'
  AND ($1::timestamptz IS NULL OR d.created_at >= $1::timestamptz)
  AND d.created_at < $2::timestamptz
GROUP BY rc.code, rc.label, rc.category, rc.sort_order
ORDER BY count DESC, rc.sort_order ASC, rc.label ASC
`

type ListAnalyticsReasonCodesParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type ListAnalyticsReasonCodesRow struct {
	Code     string `json:"code"`
	Label    string `json:"label"`
	Category string `json:"category"`
	Count    int32  `json:"count"`
}

func (q *Queries) ListAnalyticsReasonCodes(ctx context.Context, arg ListAnalyticsReasonCodesParams) ([]ListAnalyticsReasonCodesRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsReasonCodes, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalyticsReasonCodesRow
	for rows.Next() {
		var i ListAnalyticsReasonCodesRow
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.Category,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsRiskQueue = `-- name: ListAnalyticsRiskQueue :many
SELECT
    c.id::text AS case_id,
    c.case_reference,
    c.status,
    COALESCE(ml.customer_status, '') AS customer_status,
    COALESCE(o.name, '') AS organization_name,
    EXTRACT(EPOCH FROM ($1::timestamptz - c.created_at))::int AS age_seconds,
    array_remove(ARRAY[
        CASE WHEN c.status = 'in_review' THEN 'in_review' END,
        CASE WHEN c.status = 'reopened' THEN 'reopened' END,
        CASE WHEN d.decision = 'stop' THEN 'stop_decision' END,
        CASE WHEN d.decision = 'review' THEN 'review_decision' END,
        CASE WHEN COUNT(e.id) FILTER (WHERE e.evidence_status = 'confirmed') = 0 THEN 'no_confirmed_evidence' END,
        CASE WHEN COUNT(e.id) FILTER (WHERE e.evidence_status = 'conflicting') > 0 THEN 'conflicting_evidence' END
    ], NULL)::text[] AS risk_reasons
FROM ops.case_records c
LEFT JOIN pilot.matter_links ml ON ml.case_id = c.id
LEFT JOIN pilot.organizations o ON o.id = ml.organization_id
LEFT JOIN ops.case_decisions d ON d.case_id = c.id AND d.status = 'current'
    AND d.created_at < $1::timestamptz
LEFT JOIN ops.case_evidence_items e ON e.case_id = c.id
    AND e.created_at < $1::timestamptz
WHERE ($2::timestamptz IS NULL OR c.created_at >= $2::timestamptz)
  AND c.created_at < $1::timestamptz
  AND (
      c.status IN ('in_review', 'reopened')
      OR d.decision IN ('stop', 'review')
      OR EXISTS (
          SELECT 1
          FROM ops.case_evidence_items ce
          WHERE ce.case_id = c.id
            AND ce.evidence_status = 'conflicting'
            AND ce.created_at < $1::timestamptz
      )
      OR NOT EXISTS (
          SELECT 1
          FROM ops.case_evidence_items ce
          WHERE ce.case_id = c.id
            AND ce.evidence_status = 'confirmed'
            AND ce.created_at < $1::timestamptz
      )
  )
GROUP BY c.id, c.case_reference, c.status, ml.customer_status, o.name, c.created_at, d.decision
ORDER BY age_seconds DESC
LIMIT 12
`

type ListAnalyticsRiskQueueParams struct {
	ToAt   pgtype.Timestamptz `json:"to_at"`
	FromAt pgtype.Timestamptz `json:"from_at"`
}

type ListAnalyticsRiskQueueRow struct {
	CaseID           string   `json:"case_id"`
	CaseReference    string   `json:"case_reference"`
	Status           string   `json:"status"`
	CustomerStatus   string   `json:"customer_status"`
	OrganizationName string   `json:"organization_name"`
	AgeSeconds       int32    `json:"age_seconds"`
	RiskReasons      []string `json:"risk_reasons"`
}

func (q *Queries) ListAnalyticsRiskQueue(ctx context.Context, arg ListAnalyticsRiskQueueParams) ([]ListAnalyticsRiskQueueRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsRiskQueue, arg.ToAt, arg.FromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalyticsRiskQueueRow
	for rows.Next() {
		var i ListAnalyticsRiskQueueRow
		if err := rows.Scan(
			&i.CaseID,
			&i.CaseReference,
			&i.Status,
			&i.CustomerStatus,
			&i.OrganizationName,
			&i.AgeSeconds,
			&i.RiskReasons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
