// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCaseEvidence = `-- name: AddCaseEvidence :one
INSERT INTO ops.case_evidence_items (
    case_id, evidence_type, source_type, source_reference, external_reference,
    excerpt, extracted_facts, evidence_status, analyst_note, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, case_id, evidence_type, source_type, source_reference, external_reference,
    excerpt, extracted_facts, evidence_status, analyst_note, created_by, created_at
`

type AddCaseEvidenceParams struct {
	CaseID            pgtype.UUID `json:"case_id"`
	EvidenceType      string      `json:"evidence_type"`
	SourceType        string      `json:"source_type"`
	SourceReference   string      `json:"source_reference"`
	ExternalReference pgtype.Text `json:"external_reference"`
	Excerpt           pgtype.Text `json:"excerpt"`
	ExtractedFacts    []byte      `json:"extracted_facts"`
	EvidenceStatus    string      `json:"evidence_status"`
	AnalystNote       pgtype.Text `json:"analyst_note"`
	CreatedBy         string      `json:"created_by"`
}

func (q *Queries) AddCaseEvidence(ctx context.Context, arg AddCaseEvidenceParams) (OpsCaseEvidenceItem, error) {
	row := q.db.QueryRow(ctx, addCaseEvidence,
		arg.CaseID,
		arg.EvidenceType,
		arg.SourceType,
		arg.SourceReference,
		arg.ExternalReference,
		arg.Excerpt,
		arg.ExtractedFacts,
		arg.EvidenceStatus,
		arg.AnalystNote,
		arg.CreatedBy,
	)
	var i OpsCaseEvidenceItem
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.EvidenceType,
		&i.SourceType,
		&i.SourceReference,
		&i.ExternalReference,
		&i.Excerpt,
		&i.ExtractedFacts,
		&i.EvidenceStatus,
		&i.AnalystNote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const addCaseParty = `-- name: AddCaseParty :one
INSERT INTO ops.case_parties (case_id, role, entity_type, display_name, identifier, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, case_id, role, entity_type, display_name, identifier, note, created_by, created_at
`

type AddCasePartyParams struct {
	CaseID      pgtype.UUID `json:"case_id"`
	Role        string      `json:"role"`
	EntityType  string      `json:"entity_type"`
	DisplayName string      `json:"display_name"`
	Identifier  pgtype.Text `json:"identifier"`
	Note        pgtype.Text `json:"note"`
	CreatedBy   string      `json:"created_by"`
}

func (q *Queries) AddCaseParty(ctx context.Context, arg AddCasePartyParams) (OpsCaseParty, error) {
	row := q.db.QueryRow(ctx, addCaseParty,
		arg.CaseID,
		arg.Role,
		arg.EntityType,
		arg.DisplayName,
		arg.Identifier,
		arg.Note,
		arg.CreatedBy,
	)
	var i OpsCaseParty
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Role,
		&i.EntityType,
		&i.DisplayName,
		&i.Identifier,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const addDecisionProposalReasonCode = `-- name: AddDecisionProposalReasonCode :exec
INSERT INTO ops.case_decision_proposal_reason_codes (proposal_id, reason_code)
VALUES ($1, $2)
`

type AddDecisionProposalReasonCodeParams struct {
	ProposalID pgtype.UUID `json:"proposal_id"`
	ReasonCode string      `json:"reason_code"`
}

func (q *Queries) AddDecisionProposalReasonCode(ctx context.Context, arg AddDecisionProposalReasonCodeParams) error {
	_, err := q.db.Exec(ctx, addDecisionProposalReasonCode, arg.ProposalID, arg.ReasonCode)
	return err
}

const addDecisionReasonCode = `-- name: AddDecisionReasonCode :exec
INSERT INTO ops.case_decision_reason_codes (decision_id, reason_code)
VALUES ($1, $2)
`

type AddDecisionReasonCodeParams struct {
	DecisionID pgtype.UUID `json:"decision_id"`
	ReasonCode string      `json:"reason_code"`
}

func (q *Queries) AddDecisionReasonCode(ctx context.Context, arg AddDecisionReasonCodeParams) error {
	_, err := q.db.Exec(ctx, addDecisionReasonCode, arg.DecisionID, arg.ReasonCode)
	return err
}

const closeCaseUnresolved = `-- name: CloseCaseUnresolved :one
UPDATE ops.case_records
SET status = 'closed_unresolved', resolved_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, intake_note, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
`

type CloseCaseUnresolvedRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CloseCaseUnresolved(ctx context.Context, id pgtype.UUID) (CloseCaseUnresolvedRow, error) {
	row := q.db.QueryRow(ctx, closeCaseUnresolved, id)
	var i CloseCaseUnresolvedRow
	err := row.Scan(
		&i.ID,
		&i.CaseReference,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.MatterReference,
		&i.IntakeNote,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.LinkedSeedPropertyID,
		&i.LinkedPropertyID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmCasePropertyMatch = `-- name: ConfirmCasePropertyMatch :one
UPDATE ops.case_property_matches
SET status = 'confirmed', confirmed_by = $3, confirmed_at = NOW()
WHERE case_id = $1 AND id = $2
RETURNING id, case_id, seed_property_id, match_source, confidence, status, confirmed_by, confirmed_at, created_at
`

type ConfirmCasePropertyMatchParams struct {
	CaseID      pgtype.UUID `json:"case_id"`
	ID          pgtype.UUID `json:"id"`
	ConfirmedBy pgtype.Text `json:"confirmed_by"`
}

func (q *Queries) ConfirmCasePropertyMatch(ctx context.Context, arg ConfirmCasePropertyMatchParams) (OpsCasePropertyMatch, error) {
	row := q.db.QueryRow(ctx, confirmCasePropertyMatch, arg.CaseID, arg.ID, arg.ConfirmedBy)
	var i OpsCasePropertyMatch
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.SeedPropertyID,
		&i.MatchSource,
		&i.Confidence,
		&i.Status,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAcceptedDecisionFromProposal = `-- name: CreateAcceptedDecisionFromProposal :one
INSERT INTO ops.case_decisions (case_id, decision, note, status, created_by, decision_source, proposal_id)
VALUES ($1, $2, $3, 'current', $4, 'accepted_proposal', $5)
RETURNING id, case_id, decision, note, status, created_by, created_at, superseded_at, decision_source, proposal_id
`

type CreateAcceptedDecisionFromProposalParams struct {
	CaseID     pgtype.UUID `json:"case_id"`
	Decision   string      `json:"decision"`
	Note       string      `json:"note"`
	CreatedBy  string      `json:"created_by"`
	ProposalID pgtype.UUID `json:"proposal_id"`
}

func (q *Queries) CreateAcceptedDecisionFromProposal(ctx context.Context, arg CreateAcceptedDecisionFromProposalParams) (OpsCaseDecision, error) {
	row := q.db.QueryRow(ctx, createAcceptedDecisionFromProposal,
		arg.CaseID,
		arg.Decision,
		arg.Note,
		arg.CreatedBy,
		arg.ProposalID,
	)
	var i OpsCaseDecision
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Decision,
		&i.Note,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.DecisionSource,
		&i.ProposalID,
	)
	return i, err
}

const createCaseAuditEvent = `-- name: CreateCaseAuditEvent :one
INSERT INTO ops.case_audit_events (case_id, actor_id, event_type, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, case_id, actor_id, event_type, metadata, created_at
`

type CreateCaseAuditEventParams struct {
	CaseID    pgtype.UUID `json:"case_id"`
	ActorID   string      `json:"actor_id"`
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateCaseAuditEvent(ctx context.Context, arg CreateCaseAuditEventParams) (OpsCaseAuditEvent, error) {
	row := q.db.QueryRow(ctx, createCaseAuditEvent,
		arg.CaseID,
		arg.ActorID,
		arg.EventType,
		arg.Metadata,
	)
	var i OpsCaseAuditEvent
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ActorID,
		&i.EventType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createCaseDecision = `-- name: CreateCaseDecision :one
INSERT INTO ops.case_decisions (case_id, decision, note, status, created_by, decision_source, proposal_id)
VALUES ($1, $2, $3, 'current', $4, $5, $6)
RETURNING id, case_id, decision, note, status, created_by, created_at, superseded_at, decision_source, proposal_id
`

type CreateCaseDecisionParams struct {
	CaseID         pgtype.UUID `json:"case_id"`
	Decision       string      `json:"decision"`
	Note           string      `json:"note"`
	CreatedBy      string      `json:"created_by"`
	DecisionSource string      `json:"decision_source"`
	ProposalID     pgtype.UUID `json:"proposal_id"`
}

func (q *Queries) CreateCaseDecision(ctx context.Context, arg CreateCaseDecisionParams) (OpsCaseDecision, error) {
	row := q.db.QueryRow(ctx, createCaseDecision,
		arg.CaseID,
		arg.Decision,
		arg.Note,
		arg.CreatedBy,
		arg.DecisionSource,
		arg.ProposalID,
	)
	var i OpsCaseDecision
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Decision,
		&i.Note,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.DecisionSource,
		&i.ProposalID,
	)
	return i, err
}

const createCaseRecord = `-- name: CreateCaseRecord :one
INSERT INTO ops.case_records (
    case_reference,
    property_description,
    locality_or_area,
    municipality_or_deeds_office,
    title_reference,
    matter_reference,
    intake_note,
    status,
    assignee_id,
    created_by,
    linked_property_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, 'open', $8, $8, $9)
RETURNING id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, intake_note, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
`

type CreateCaseRecordParams struct {
	CaseReference             string      `json:"case_reference"`
	PropertyDescription       string      `json:"property_description"`
	LocalityOrArea            string      `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string      `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text `json:"title_reference"`
	MatterReference           pgtype.Text `json:"matter_reference"`
	IntakeNote                pgtype.Text `json:"intake_note"`
	AssigneeID                string      `json:"assignee_id"`
	LinkedPropertyID          pgtype.UUID `json:"linked_property_id"`
}

type CreateCaseRecordRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCaseRecord(ctx context.Context, arg CreateCaseRecordParams) (CreateCaseRecordRow, error) {
	row := q.db.QueryRow(ctx, createCaseRecord,
		arg.CaseReference,
		arg.PropertyDescription,
		arg.LocalityOrArea,
		arg.MunicipalityOrDeedsOffice,
		arg.TitleReference,
		arg.MatterReference,
		arg.IntakeNote,
		arg.AssigneeID,
		arg.LinkedPropertyID,
	)
	var i CreateCaseRecordRow
	err := row.Scan(
		&i.ID,
		&i.CaseReference,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.MatterReference,
		&i.IntakeNote,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.LinkedSeedPropertyID,
		&i.LinkedPropertyID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDecisionProposal = `-- name: CreateDecisionProposal :one
INSERT INTO ops.case_decision_proposals (case_id, engine_version, decision, summary, explanation, status)
VALUES ($1, $2, $3, $4, $5, 'current')
RETURNING id, case_id, engine_version, decision, summary, explanation, status, created_at, superseded_at
`

type CreateDecisionProposalParams struct {
	CaseID        pgtype.UUID `json:"case_id"`
	EngineVersion string      `json:"engine_version"`
	Decision      string      `json:"decision"`
	Summary       string      `json:"summary"`
	Explanation   []byte      `json:"explanation"`
}

func (q *Queries) CreateDecisionProposal(ctx context.Context, arg CreateDecisionProposalParams) (OpsCaseDecisionProposal, error) {
	row := q.db.QueryRow(ctx, createDecisionProposal,
		arg.CaseID,
		arg.EngineVersion,
		arg.Decision,
		arg.Summary,
		arg.Explanation,
	)
	var i OpsCaseDecisionProposal
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.EngineVersion,
		&i.Decision,
		&i.Summary,
		&i.Explanation,
		&i.Status,
		&i.CreatedAt,
		&i.SupersededAt,
	)
	return i, err
}

const createPropertyMatch = `-- name: CreatePropertyMatch :one
INSERT INTO ops.case_property_matches (case_id, seed_property_id, match_source, confidence, status)
VALUES ($1, $2, $3, $4, 'candidate')
RETURNING id, case_id, seed_property_id, match_source, confidence, status, confirmed_by, confirmed_at, created_at
`

type CreatePropertyMatchParams struct {
	CaseID         pgtype.UUID    `json:"case_id"`
	SeedPropertyID pgtype.UUID    `json:"seed_property_id"`
	MatchSource    string         `json:"match_source"`
	Confidence     pgtype.Numeric `json:"confidence"`
}

func (q *Queries) CreatePropertyMatch(ctx context.Context, arg CreatePropertyMatchParams) (OpsCasePropertyMatch, error) {
	row := q.db.QueryRow(ctx, createPropertyMatch,
		arg.CaseID,
		arg.SeedPropertyID,
		arg.MatchSource,
		arg.Confidence,
	)
	var i OpsCasePropertyMatch
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.SeedPropertyID,
		&i.MatchSource,
		&i.Confidence,
		&i.Status,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalyst = `-- name: GetAnalyst :one
SELECT id, display_name, email, active, created_at
FROM ops.analysts
WHERE id = $1 AND active = TRUE
`

func (q *Queries) GetAnalyst(ctx context.Context, id string) (OpsAnalyst, error) {
	row := q.db.QueryRow(ctx, getAnalyst, id)
	var i OpsAnalyst
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCaseRecord = `-- name: GetCaseRecord :one
SELECT id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, intake_note, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
FROM ops.case_records
WHERE id = $1
`

type GetCaseRecordRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCaseRecord(ctx context.Context, id pgtype.UUID) (GetCaseRecordRow, error) {
	row := q.db.QueryRow(ctx, getCaseRecord, id)
	var i GetCaseRecordRow
	err := row.Scan(
		&i.ID,
		&i.CaseReference,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.MatterReference,
		&i.IntakeNote,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.LinkedSeedPropertyID,
		&i.LinkedPropertyID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentDecisionProposal = `-- name: GetCurrentDecisionProposal :one
SELECT id, case_id, engine_version, decision, summary, explanation, status, created_at, superseded_at
FROM ops.case_decision_proposals
WHERE case_id = $1 AND status = 'current'
`

func (q *Queries) GetCurrentDecisionProposal(ctx context.Context, caseID pgtype.UUID) (OpsCaseDecisionProposal, error) {
	row := q.db.QueryRow(ctx, getCurrentDecisionProposal, caseID)
	var i OpsCaseDecisionProposal
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.EngineVersion,
		&i.Decision,
		&i.Summary,
		&i.Explanation,
		&i.Status,
		&i.CreatedAt,
		&i.SupersededAt,
	)
	return i, err
}

const getSeedProperty = `-- name: GetSeedProperty :one
SELECT id, property_description, locality_or_area, municipality_or_deeds_office,
       title_reference, current_owner_name, status_summary, seeded_risk, created_at
FROM ops.seed_properties
WHERE id = $1
`

func (q *Queries) GetSeedProperty(ctx context.Context, id pgtype.UUID) (OpsSeedProperty, error) {
	row := q.db.QueryRow(ctx, getSeedProperty, id)
	var i OpsSeedProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.CurrentOwnerName,
		&i.StatusSummary,
		&i.SeededRisk,
		&i.CreatedAt,
	)
	return i, err
}

const linkCaseSeedProperty = `-- name: LinkCaseSeedProperty :one
UPDATE ops.case_records
SET linked_seed_property_id = $2, status = 'in_review', updated_at = NOW()
WHERE id = $1
RETURNING id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, intake_note, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
`

type LinkCaseSeedPropertyParams struct {
	ID                   pgtype.UUID `json:"id"`
	LinkedSeedPropertyID pgtype.UUID `json:"linked_seed_property_id"`
}

type LinkCaseSeedPropertyRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LinkCaseSeedProperty(ctx context.Context, arg LinkCaseSeedPropertyParams) (LinkCaseSeedPropertyRow, error) {
	row := q.db.QueryRow(ctx, linkCaseSeedProperty, arg.ID, arg.LinkedSeedPropertyID)
	var i LinkCaseSeedPropertyRow
	err := row.Scan(
		&i.ID,
		&i.CaseReference,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.MatterReference,
		&i.IntakeNote,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.LinkedSeedPropertyID,
		&i.LinkedPropertyID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnalysts = `-- name: ListAnalysts :many
SELECT id, display_name, email, active, created_at
FROM ops.analysts
WHERE active = TRUE
ORDER BY display_name
`

func (q *Queries) ListAnalysts(ctx context.Context) ([]OpsAnalyst, error) {
	rows, err := q.db.Query(ctx, listAnalysts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsAnalyst
	for rows.Next() {
		var i OpsAnalyst
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaseAuditEvents = `-- name: ListCaseAuditEvents :many
SELECT id, case_id, actor_id, event_type, metadata, created_at
FROM ops.case_audit_events
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCaseAuditEvents(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseAuditEvent, error) {
	rows, err := q.db.Query(ctx, listCaseAuditEvents, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsCaseAuditEvent
	for rows.Next() {
		var i OpsCaseAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.ActorID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaseDecisions = `-- name: ListCaseDecisions :many
SELECT id, case_id, decision, note, status, created_by, created_at, superseded_at, decision_source, proposal_id
FROM ops.case_decisions
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCaseDecisions(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseDecision, error) {
	rows, err := q.db.Query(ctx, listCaseDecisions, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsCaseDecision
	for rows.Next() {
		var i OpsCaseDecision
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Decision,
			&i.Note,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.SupersededAt,
			&i.DecisionSource,
			&i.ProposalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaseEvidence = `-- name: ListCaseEvidence :many
SELECT id, case_id, evidence_type, source_type, source_reference, external_reference,
    excerpt, extracted_facts, evidence_status, analyst_note, created_by, created_at
FROM ops.case_evidence_items
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCaseEvidence(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseEvidenceItem, error) {
	rows, err := q.db.Query(ctx, listCaseEvidence, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsCaseEvidenceItem
	for rows.Next() {
		var i OpsCaseEvidenceItem
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.EvidenceType,
			&i.SourceType,
			&i.SourceReference,
			&i.ExternalReference,
			&i.Excerpt,
			&i.ExtractedFacts,
			&i.EvidenceStatus,
			&i.AnalystNote,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaseParties = `-- name: ListCaseParties :many
SELECT id, case_id, role, entity_type, display_name, identifier, note, created_by, created_at
FROM ops.case_parties
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCaseParties(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseParty, error) {
	rows, err := q.db.Query(ctx, listCaseParties, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsCaseParty
	for rows.Next() {
		var i OpsCaseParty
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Role,
			&i.EntityType,
			&i.DisplayName,
			&i.Identifier,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCasePropertyMatches = `-- name: ListCasePropertyMatches :many
SELECT id, case_id, seed_property_id, match_source, confidence, status, confirmed_by, confirmed_at, created_at
FROM ops.case_property_matches
WHERE case_id = $1
ORDER BY confidence DESC, created_at
`

func (q *Queries) ListCasePropertyMatches(ctx context.Context, caseID pgtype.UUID) ([]OpsCasePropertyMatch, error) {
	rows, err := q.db.Query(ctx, listCasePropertyMatches, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsCasePropertyMatch
	for rows.Next() {
		var i OpsCasePropertyMatch
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.SeedPropertyID,
			&i.MatchSource,
			&i.Confidence,
			&i.Status,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaseSummaries = `-- name: ListCaseSummaries :many
SELECT id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
FROM ops.case_records
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR assignee_id = $2::text)
ORDER BY updated_at DESC
LIMIT $3
`

type ListCaseSummariesParams struct {
	Status     pgtype.Text `json:"status"`
	AssigneeID pgtype.Text `json:"assignee_id"`
	Limit      int32       `json:"limit"`
}

type ListCaseSummariesRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCaseSummaries(ctx context.Context, arg ListCaseSummariesParams) ([]ListCaseSummariesRow, error) {
	rows, err := q.db.Query(ctx, listCaseSummaries, arg.Status, arg.AssigneeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCaseSummariesRow
	for rows.Next() {
		var i ListCaseSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseReference,
			&i.PropertyDescription,
			&i.LocalityOrArea,
			&i.MunicipalityOrDeedsOffice,
			&i.TitleReference,
			&i.MatterReference,
			&i.Status,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.LinkedSeedPropertyID,
			&i.LinkedPropertyID,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionProposalReasonCodes = `-- name: ListDecisionProposalReasonCodes :many
SELECT rc.code, rc.label, rc.category, rc.is_hard_block, rc.active, rc.sort_order, rc.created_at
FROM ops.case_decision_proposal_reason_codes prc
JOIN ops.reason_codes rc ON rc.code = prc.reason_code
WHERE prc.proposal_id = $1
ORDER BY rc.sort_order
`

func (q *Queries) ListDecisionProposalReasonCodes(ctx context.Context, proposalID pgtype.UUID) ([]OpsReasonCode, error) {
	rows, err := q.db.Query(ctx, listDecisionProposalReasonCodes, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsReasonCode
	for rows.Next() {
		var i OpsReasonCode
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.Category,
			&i.IsHardBlock,
			&i.Active,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionReasonCodes = `-- name: ListDecisionReasonCodes :many
SELECT drr.decision_id, rc.code, rc.label, rc.category, rc.is_hard_block, rc.active, rc.sort_order, rc.created_at
FROM ops.case_decision_reason_codes drr
JOIN ops.reason_codes rc ON rc.code = drr.reason_code
WHERE drr.decision_id = $1
ORDER BY rc.sort_order
`

type ListDecisionReasonCodesRow struct {
	DecisionID  pgtype.UUID        `json:"decision_id"`
	Code        string             `json:"code"`
	Label       string             `json:"label"`
	Category    string             `json:"category"`
	IsHardBlock bool               `json:"is_hard_block"`
	Active      bool               `json:"active"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionReasonCodes(ctx context.Context, decisionID pgtype.UUID) ([]ListDecisionReasonCodesRow, error) {
	rows, err := q.db.Query(ctx, listDecisionReasonCodes, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionReasonCodesRow
	for rows.Next() {
		var i ListDecisionReasonCodesRow
		if err := rows.Scan(
			&i.DecisionID,
			&i.Code,
			&i.Label,
			&i.Category,
			&i.IsHardBlock,
			&i.Active,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilotCaseContexts = `-- name: ListPilotCaseContexts :many
SELECT ml.case_id,
       ml.id AS matter_id,
       ml.customer_reference,
       ml.customer_status,
       ml.submitted_at,
       o.id AS organization_id,
       o.name AS organization_name
FROM pilot.matter_links ml
JOIN pilot.organizations o ON o.id = ml.organization_id
WHERE $1::uuid IS NULL
   OR ml.organization_id = $1::uuid
`

type ListPilotCaseContextsRow struct {
	CaseID            pgtype.UUID        `json:"case_id"`
	MatterID          pgtype.UUID        `json:"matter_id"`
	CustomerReference pgtype.Text        `json:"customer_reference"`
	CustomerStatus    string             `json:"customer_status"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	OrganizationName  string             `json:"organization_name"`
}

func (q *Queries) ListPilotCaseContexts(ctx context.Context, organizationID pgtype.UUID) ([]ListPilotCaseContextsRow, error) {
	rows, err := q.db.Query(ctx, listPilotCaseContexts, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPilotCaseContextsRow
	for rows.Next() {
		var i ListPilotCaseContextsRow
		if err := rows.Scan(
			&i.CaseID,
			&i.MatterID,
			&i.CustomerReference,
			&i.CustomerStatus,
			&i.SubmittedAt,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReasonCodes = `-- name: ListReasonCodes :many
SELECT code, label, category, is_hard_block, active, sort_order, created_at
FROM ops.reason_codes
WHERE active = TRUE
ORDER BY sort_order
`

func (q *Queries) ListReasonCodes(ctx context.Context) ([]OpsReasonCode, error) {
	rows, err := q.db.Query(ctx, listReasonCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsReasonCode
	for rows.Next() {
		var i OpsReasonCode
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.Category,
			&i.IsHardBlock,
			&i.Active,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeedPropertyMatches = `-- name: ListSeedPropertyMatches :many
SELECT id, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, current_owner_name, status_summary, seeded_risk, created_at
FROM ops.seed_properties
WHERE lower(property_description) LIKE '%' || lower($1) || '%'
   OR lower(locality_or_area) LIKE '%' || lower($2) || '%'
   OR lower(municipality_or_deeds_office) LIKE '%' || lower($3) || '%'
ORDER BY
    CASE WHEN lower(property_description) = lower($1) THEN 0 ELSE 1 END,
    created_at
LIMIT 5
`

type ListSeedPropertyMatchesParams struct {
	Lower   string `json:"lower"`
	Lower_2 string `json:"lower_2"`
	Lower_3 string `json:"lower_3"`
}

func (q *Queries) ListSeedPropertyMatches(ctx context.Context, arg ListSeedPropertyMatchesParams) ([]OpsSeedProperty, error) {
	rows, err := q.db.Query(ctx, listSeedPropertyMatches, arg.Lower, arg.Lower_2, arg.Lower_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsSeedProperty
	for rows.Next() {
		var i OpsSeedProperty
		if err := rows.Scan(
			&i.ID,
			&i.PropertyDescription,
			&i.LocalityOrArea,
			&i.MunicipalityOrDeedsOffice,
			&i.TitleReference,
			&i.CurrentOwnerName,
			&i.StatusSummary,
			&i.SeededRisk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCase = `-- name: ReassignCase :one
UPDATE ops.case_records
SET assignee_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, intake_note, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
`

type ReassignCaseParams struct {
	ID         pgtype.UUID `json:"id"`
	AssigneeID string      `json:"assignee_id"`
}

type ReassignCaseRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReassignCase(ctx context.Context, arg ReassignCaseParams) (ReassignCaseRow, error) {
	row := q.db.QueryRow(ctx, reassignCase, arg.ID, arg.AssigneeID)
	var i ReassignCaseRow
	err := row.Scan(
		&i.ID,
		&i.CaseReference,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.MatterReference,
		&i.IntakeNote,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.LinkedSeedPropertyID,
		&i.LinkedPropertyID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectCasePropertyMatches = `-- name: RejectCasePropertyMatches :exec
UPDATE ops.case_property_matches
SET status = 'rejected'
WHERE case_id = $1 AND status = 'candidate'
`

func (q *Queries) RejectCasePropertyMatches(ctx context.Context, caseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectCasePropertyMatches, caseID)
	return err
}

const reopenCase = `-- name: ReopenCase :one
UPDATE ops.case_records
SET status = 'reopened', resolved_at = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, intake_note, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
`

type ReopenCaseRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReopenCase(ctx context.Context, id pgtype.UUID) (ReopenCaseRow, error) {
	row := q.db.QueryRow(ctx, reopenCase, id)
	var i ReopenCaseRow
	err := row.Scan(
		&i.ID,
		&i.CaseReference,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.MatterReference,
		&i.IntakeNote,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.LinkedSeedPropertyID,
		&i.LinkedPropertyID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveCase = `-- name: ResolveCase :one
UPDATE ops.case_records
SET status = 'resolved', resolved_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, case_reference, property_description, locality_or_area, municipality_or_deeds_office,
    title_reference, matter_reference, intake_note, status, assignee_id, created_by,
    linked_seed_property_id, linked_property_id, resolved_at, created_at, updated_at
`

type ResolveCaseRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResolveCase(ctx context.Context, id pgtype.UUID) (ResolveCaseRow, error) {
	row := q.db.QueryRow(ctx, resolveCase, id)
	var i ResolveCaseRow
	err := row.Scan(
		&i.ID,
		&i.CaseReference,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.MatterReference,
		&i.IntakeNote,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.LinkedSeedPropertyID,
		&i.LinkedPropertyID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeCurrentDecisionProposal = `-- name: SupersedeCurrentDecisionProposal :exec
UPDATE ops.case_decision_proposals
SET status = 'superseded', superseded_at = NOW()
WHERE case_id = $1 AND status = 'current'
`

func (q *Queries) SupersedeCurrentDecisionProposal(ctx context.Context, caseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedeCurrentDecisionProposal, caseID)
	return err
}

const supersedeCurrentDecisions = `-- name: SupersedeCurrentDecisions :exec
UPDATE ops.case_decisions
SET status = 'superseded', superseded_at = NOW()
WHERE case_id = $1 AND status = 'current'
`

func (q *Queries) SupersedeCurrentDecisions(ctx context.Context, caseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedeCurrentDecisions, caseID)
	return err
}
