// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisioning.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDecisioningPropertySnapshot = `-- name: GetDecisioningPropertySnapshot :one
SELECT p.id AS property_id,
       p.latest_title_reference,
       COALESCE(MAX(tr.registration_status), ''::text)::text AS title_status,
       COALESCE(BOOL_OR(lower(e.status) = 'active'), FALSE)::bool AS has_active_encumbrance,
       COALESCE(BOOL_OR(q.id IS NOT NULL), FALSE)::bool AS has_quarantined_rows,
       COUNT(DISTINCT sl.id)::int AS source_link_count
FROM core.properties p
LEFT JOIN core.title_registrations tr ON tr.property_id = p.id
LEFT JOIN core.encumbrances e ON e.property_id = p.id
LEFT JOIN core.source_links sl ON sl.property_id = p.id
LEFT JOIN stage.quarantined_records q ON q.source_record_id = sl.source_record_id
WHERE p.id = $1
GROUP BY p.id, p.latest_title_reference
`

type GetDecisioningPropertySnapshotRow struct {
	PropertyID           pgtype.UUID `json:"property_id"`
	LatestTitleReference string      `json:"latest_title_reference"`
	TitleStatus          string      `json:"title_status"`
	HasActiveEncumbrance bool        `json:"has_active_encumbrance"`
	HasQuarantinedRows   bool        `json:"has_quarantined_rows"`
	SourceLinkCount      int32       `json:"source_link_count"`
}

func (q *Queries) GetDecisioningPropertySnapshot(ctx context.Context, id pgtype.UUID) (GetDecisioningPropertySnapshotRow, error) {
	row := q.db.QueryRow(ctx, getDecisioningPropertySnapshot, id)
	var i GetDecisioningPropertySnapshotRow
	err := row.Scan(
		&i.PropertyID,
		&i.LatestTitleReference,
		&i.TitleStatus,
		&i.HasActiveEncumbrance,
		&i.HasQuarantinedRows,
		&i.SourceLinkCount,
	)
	return i, err
}

const listDecisioningPropertyParties = `-- name: ListDecisioningPropertyParties :many
SELECT party_name, party_role
FROM core.property_parties
WHERE property_id = $1
ORDER BY party_role, party_name
`

type ListDecisioningPropertyPartiesRow struct {
	PartyName string `json:"party_name"`
	PartyRole string `json:"party_role"`
}

func (q *Queries) ListDecisioningPropertyParties(ctx context.Context, propertyID pgtype.UUID) ([]ListDecisioningPropertyPartiesRow, error) {
	rows, err := q.db.Query(ctx, listDecisioningPropertyParties, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisioningPropertyPartiesRow
	for rows.Next() {
		var i ListDecisioningPropertyPartiesRow
		if err := rows.Scan(&i.PartyName, &i.PartyRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
