// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OpsJob struct {
	ID             pgtype.UUID        `json:"id"`
	RunID          pgtype.UUID        `json:"run_id"`
	JobKind        string             `json:"job_kind"`
	Status         string             `json:"status"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	RetryCount     int32              `json:"retry_count"`
	Checkpoint     []byte             `json:"checkpoint"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OpsJobAttempt struct {
	ID            pgtype.UUID        `json:"id"`
	JobID         pgtype.UUID        `json:"job_id"`
	AttemptNumber int32              `json:"attempt_number"`
	WorkerID      string             `json:"worker_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Outcome       string             `json:"outcome"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
}

type OpsRun struct {
	ID         pgtype.UUID        `json:"id"`
	BatchID    pgtype.UUID        `json:"batch_id"`
	RunType    string             `json:"run_type"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RawBatch struct {
	ID             pgtype.UUID        `json:"id"`
	SourceName     string             `json:"source_name"`
	SourceBatchKey string             `json:"source_batch_key"`
	PayloadUri     pgtype.Text        `json:"payload_uri"`
	PayloadSha256  string             `json:"payload_sha256"`
	ImportedAt     pgtype.Timestamptz `json:"imported_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReadPropertySummary struct {
	PropertyID     pgtype.UUID        `json:"property_id"`
	TitleReference string             `json:"title_reference"`
	Status         string             `json:"status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
