// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreEncumbrance struct {
	ID              pgtype.UUID        `json:"id"`
	PropertyID      pgtype.UUID        `json:"property_id"`
	EncumbranceType string             `json:"encumbrance_type"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CoreProperty struct {
	ID                        pgtype.UUID        `json:"id"`
	PropertyFingerprint       string             `json:"property_fingerprint"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	PropertyDescription       string             `json:"property_description"`
	LatestTitleReference      string             `json:"latest_title_reference"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type CorePropertyParty struct {
	ID         pgtype.UUID        `json:"id"`
	PropertyID pgtype.UUID        `json:"property_id"`
	PartyName  string             `json:"party_name"`
	PartyRole  string             `json:"party_role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CoreSourceLink struct {
	ID             pgtype.UUID        `json:"id"`
	PropertyID     pgtype.UUID        `json:"property_id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	SourceRecordID pgtype.UUID        `json:"source_record_id"`
	FactTable      string             `json:"fact_table"`
	FactID         pgtype.UUID        `json:"fact_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CoreTitleRegistration struct {
	ID                 pgtype.UUID        `json:"id"`
	PropertyID         pgtype.UUID        `json:"property_id"`
	TitleReference     string             `json:"title_reference"`
	RegistrationStatus string             `json:"registration_status"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type OpsAnalyst struct {
	ID          string             `json:"id"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OpsCaseAuditEvent struct {
	ID        pgtype.UUID        `json:"id"`
	CaseID    pgtype.UUID        `json:"case_id"`
	ActorID   string             `json:"actor_id"`
	EventType string             `json:"event_type"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OpsCaseDecision struct {
	ID             pgtype.UUID        `json:"id"`
	CaseID         pgtype.UUID        `json:"case_id"`
	Decision       string             `json:"decision"`
	Note           string             `json:"note"`
	Status         string             `json:"status"`
	CreatedBy      string             `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SupersededAt   pgtype.Timestamptz `json:"superseded_at"`
	DecisionSource string             `json:"decision_source"`
	ProposalID     pgtype.UUID        `json:"proposal_id"`
}

type OpsCaseDecisionProposal struct {
	ID            pgtype.UUID        `json:"id"`
	CaseID        pgtype.UUID        `json:"case_id"`
	EngineVersion string             `json:"engine_version"`
	Decision      string             `json:"decision"`
	Summary       string             `json:"summary"`
	Explanation   []byte             `json:"explanation"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SupersededAt  pgtype.Timestamptz `json:"superseded_at"`
}

type OpsCaseDecisionProposalReasonCode struct {
	ProposalID pgtype.UUID `json:"proposal_id"`
	ReasonCode string      `json:"reason_code"`
}

type OpsCaseDecisionReasonCode struct {
	DecisionID pgtype.UUID `json:"decision_id"`
	ReasonCode string      `json:"reason_code"`
}

type OpsCaseEvidenceItem struct {
	ID                pgtype.UUID        `json:"id"`
	CaseID            pgtype.UUID        `json:"case_id"`
	EvidenceType      string             `json:"evidence_type"`
	SourceType        string             `json:"source_type"`
	SourceReference   string             `json:"source_reference"`
	ExternalReference pgtype.Text        `json:"external_reference"`
	Excerpt           pgtype.Text        `json:"excerpt"`
	ExtractedFacts    []byte             `json:"extracted_facts"`
	EvidenceStatus    string             `json:"evidence_status"`
	AnalystNote       pgtype.Text        `json:"analyst_note"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type OpsCaseParty struct {
	ID          pgtype.UUID        `json:"id"`
	CaseID      pgtype.UUID        `json:"case_id"`
	Role        string             `json:"role"`
	EntityType  string             `json:"entity_type"`
	DisplayName string             `json:"display_name"`
	Identifier  pgtype.Text        `json:"identifier"`
	Note        pgtype.Text        `json:"note"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OpsCasePropertyMatch struct {
	ID             pgtype.UUID        `json:"id"`
	CaseID         pgtype.UUID        `json:"case_id"`
	SeedPropertyID pgtype.UUID        `json:"seed_property_id"`
	MatchSource    string             `json:"match_source"`
	Confidence     pgtype.Numeric     `json:"confidence"`
	Status         string             `json:"status"`
	ConfirmedBy    pgtype.Text        `json:"confirmed_by"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OpsCaseRecord struct {
	ID                        pgtype.UUID        `json:"id"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	MatterReference           pgtype.Text        `json:"matter_reference"`
	IntakeNote                pgtype.Text        `json:"intake_note"`
	Status                    string             `json:"status"`
	AssigneeID                string             `json:"assignee_id"`
	CreatedBy                 string             `json:"created_by"`
	LinkedSeedPropertyID      pgtype.UUID        `json:"linked_seed_property_id"`
	ResolvedAt                pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	LinkedPropertyID          pgtype.UUID        `json:"linked_property_id"`
}

type OpsJob struct {
	ID             pgtype.UUID        `json:"id"`
	RunID          pgtype.UUID        `json:"run_id"`
	JobKind        string             `json:"job_kind"`
	Status         string             `json:"status"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	RetryCount     int32              `json:"retry_count"`
	Checkpoint     []byte             `json:"checkpoint"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OpsJobAttempt struct {
	ID            pgtype.UUID        `json:"id"`
	JobID         pgtype.UUID        `json:"job_id"`
	AttemptNumber int32              `json:"attempt_number"`
	WorkerID      string             `json:"worker_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Outcome       string             `json:"outcome"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
}

type OpsReasonCode struct {
	Code        string             `json:"code"`
	Label       string             `json:"label"`
	Category    string             `json:"category"`
	IsHardBlock bool               `json:"is_hard_block"`
	Active      bool               `json:"active"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OpsRun struct {
	ID         pgtype.UUID        `json:"id"`
	BatchID    pgtype.UUID        `json:"batch_id"`
	RunType    string             `json:"run_type"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type OpsSeedProperty struct {
	ID                        pgtype.UUID        `json:"id"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	CurrentOwnerName          pgtype.Text        `json:"current_owner_name"`
	StatusSummary             string             `json:"status_summary"`
	SeededRisk                []byte             `json:"seeded_risk"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type PilotMatterLink struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	CreatedByUserID      pgtype.UUID        `json:"created_by_user_id"`
	CaseID               pgtype.UUID        `json:"case_id"`
	CustomerReference    pgtype.Text        `json:"customer_reference"`
	CustomerStatus       string             `json:"customer_status"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	LastCustomerViewedAt pgtype.Timestamptz `json:"last_customer_viewed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PilotOrganization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PilotSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type PilotSummaryExport struct {
	ID                pgtype.UUID        `json:"id"`
	MatterLinkID      pgtype.UUID        `json:"matter_link_id"`
	RequestedByUserID pgtype.UUID        `json:"requested_by_user_id"`
	Format            string             `json:"format"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PilotUser struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Email          string             `json:"email"`
	DisplayName    string             `json:"display_name"`
	Role           string             `json:"role"`
	PasswordHash   string             `json:"password_hash"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RawBatch struct {
	ID             pgtype.UUID        `json:"id"`
	SourceName     string             `json:"source_name"`
	SourceBatchKey string             `json:"source_batch_key"`
	PayloadUri     pgtype.Text        `json:"payload_uri"`
	PayloadSha256  string             `json:"payload_sha256"`
	ImportedAt     pgtype.Timestamptz `json:"imported_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RawRecord struct {
	ID            pgtype.UUID        `json:"id"`
	BatchID       pgtype.UUID        `json:"batch_id"`
	RecordKey     string             `json:"record_key"`
	RecordType    string             `json:"record_type"`
	Payload       []byte             `json:"payload"`
	PayloadSha256 string             `json:"payload_sha256"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ReadPropertySummary struct {
	PropertyID                pgtype.UUID        `json:"property_id"`
	TitleReference            string             `json:"title_reference"`
	Status                    string             `json:"status"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	CurrentOwnerName          pgtype.Text        `json:"current_owner_name"`
}

type StageEncumbranceRow struct {
	ID              pgtype.UUID        `json:"id"`
	BatchID         pgtype.UUID        `json:"batch_id"`
	SourceRecordID  pgtype.UUID        `json:"source_record_id"`
	RecordKey       string             `json:"record_key"`
	TitleReference  string             `json:"title_reference"`
	EncumbranceType string             `json:"encumbrance_type"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type StagePartyRow struct {
	ID             pgtype.UUID        `json:"id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	SourceRecordID pgtype.UUID        `json:"source_record_id"`
	RecordKey      string             `json:"record_key"`
	TitleReference string             `json:"title_reference"`
	PartyName      string             `json:"party_name"`
	PartyRole      string             `json:"party_role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StagePropertyRow struct {
	ID                        pgtype.UUID        `json:"id"`
	BatchID                   pgtype.UUID        `json:"batch_id"`
	SourceRecordID            pgtype.UUID        `json:"source_record_id"`
	RecordKey                 string             `json:"record_key"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	PropertyDescription       string             `json:"property_description"`
	TitleReference            string             `json:"title_reference"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type StageQuarantinedRecord struct {
	ID             pgtype.UUID        `json:"id"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	SourceRecordID pgtype.UUID        `json:"source_record_id"`
	RecordKey      string             `json:"record_key"`
	Reason         string             `json:"reason"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StageTitleRow struct {
	ID                 pgtype.UUID        `json:"id"`
	BatchID            pgtype.UUID        `json:"batch_id"`
	SourceRecordID     pgtype.UUID        `json:"source_record_id"`
	RecordKey          string             `json:"record_key"`
	TitleReference     string             `json:"title_reference"`
	RegistrationStatus string             `json:"registration_status"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
