// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ops_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextJob = `-- name: ClaimNextJob :one
WITH candidate AS (
    SELECT id
    FROM ops.jobs
    WHERE status = 'pending'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE ops.jobs
SET status = 'leased',
    lease_owner = $1,
    lease_expires_at = $2,
    updated_at = NOW()
WHERE id = (SELECT id FROM candidate)
RETURNING id, run_id, job_kind, status, lease_owner, lease_expires_at, retry_count, checkpoint, error_message, created_at, updated_at
`

type ClaimNextJobParams struct {
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) ClaimNextJob(ctx context.Context, arg ClaimNextJobParams) (OpsJob, error) {
	row := q.db.QueryRow(ctx, claimNextJob, arg.LeaseOwner, arg.LeaseExpiresAt)
	var i OpsJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobKind,
		&i.Status,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.Checkpoint,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO ops.runs (batch_id, run_type, status)
VALUES ($1, $2, $3)
RETURNING id, batch_id, run_type, status, started_at, finished_at, created_at, updated_at
`

type CreateRunParams struct {
	BatchID pgtype.UUID `json:"batch_id"`
	RunType string      `json:"run_type"`
	Status  string      `json:"status"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (OpsRun, error) {
	row := q.db.QueryRow(ctx, createRun, arg.BatchID, arg.RunType, arg.Status)
	var i OpsRun
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.RunType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, batch_id, run_type, status, started_at, finished_at, created_at, updated_at
FROM ops.runs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRuns(ctx context.Context, limit int32) ([]OpsRun, error) {
	rows, err := q.db.Query(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsRun
	for rows.Next() {
		var i OpsRun
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.RunType,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
