// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pilot.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPilotMatterLink = `-- name: CreatePilotMatterLink :one
INSERT INTO pilot.matter_links (
    organization_id, created_by_user_id, case_id, customer_reference, customer_status
) VALUES ($1, $2, $3, $4, 'submitted')
RETURNING id, organization_id, created_by_user_id, case_id, customer_reference, customer_status,
          submitted_at, last_customer_viewed_at, created_at, updated_at
`

type CreatePilotMatterLinkParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	CreatedByUserID   pgtype.UUID `json:"created_by_user_id"`
	CaseID            pgtype.UUID `json:"case_id"`
	CustomerReference pgtype.Text `json:"customer_reference"`
}

func (q *Queries) CreatePilotMatterLink(ctx context.Context, arg CreatePilotMatterLinkParams) (PilotMatterLink, error) {
	row := q.db.QueryRow(ctx, createPilotMatterLink,
		arg.OrganizationID,
		arg.CreatedByUserID,
		arg.CaseID,
		arg.CustomerReference,
	)
	var i PilotMatterLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.CaseID,
		&i.CustomerReference,
		&i.CustomerStatus,
		&i.SubmittedAt,
		&i.LastCustomerViewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPilotSession = `-- name: CreatePilotSession :one
INSERT INTO pilot.sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked_at
`

type CreatePilotSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePilotSession(ctx context.Context, arg CreatePilotSessionParams) (PilotSession, error) {
	row := q.db.QueryRow(ctx, createPilotSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PilotSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createPilotSummaryExport = `-- name: CreatePilotSummaryExport :one
INSERT INTO pilot.summary_exports (matter_link_id, requested_by_user_id, format)
VALUES ($1, $2, 'html_print')
RETURNING id, matter_link_id, requested_by_user_id, format, created_at
`

type CreatePilotSummaryExportParams struct {
	MatterLinkID      pgtype.UUID `json:"matter_link_id"`
	RequestedByUserID pgtype.UUID `json:"requested_by_user_id"`
}

func (q *Queries) CreatePilotSummaryExport(ctx context.Context, arg CreatePilotSummaryExportParams) (PilotSummaryExport, error) {
	row := q.db.QueryRow(ctx, createPilotSummaryExport, arg.MatterLinkID, arg.RequestedByUserID)
	var i PilotSummaryExport
	err := row.Scan(
		&i.ID,
		&i.MatterLinkID,
		&i.RequestedByUserID,
		&i.Format,
		&i.CreatedAt,
	)
	return i, err
}

const getPilotCaseContext = `-- name: GetPilotCaseContext :one
SELECT ml.id AS matter_id,
       ml.organization_id,
       o.name AS organization_name,
       ml.customer_reference,
       ml.customer_status,
       ml.submitted_at
FROM pilot.matter_links ml
JOIN pilot.organizations o ON o.id = ml.organization_id
WHERE ml.case_id = $1
`

type GetPilotCaseContextRow struct {
	MatterID          pgtype.UUID        `json:"matter_id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	OrganizationName  string             `json:"organization_name"`
	CustomerReference pgtype.Text        `json:"customer_reference"`
	CustomerStatus    string             `json:"customer_status"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) GetPilotCaseContext(ctx context.Context, caseID pgtype.UUID) (GetPilotCaseContextRow, error) {
	row := q.db.QueryRow(ctx, getPilotCaseContext, caseID)
	var i GetPilotCaseContextRow
	err := row.Scan(
		&i.MatterID,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.CustomerReference,
		&i.CustomerStatus,
		&i.SubmittedAt,
	)
	return i, err
}

const getPilotMatterLinkForOrg = `-- name: GetPilotMatterLinkForOrg :one
SELECT ml.id, ml.organization_id, ml.created_by_user_id, ml.case_id, ml.customer_reference,
       ml.customer_status, ml.submitted_at, ml.last_customer_viewed_at, ml.created_at, ml.updated_at
FROM pilot.matter_links ml
WHERE ml.id = $1 AND ml.organization_id = $2
`

type GetPilotMatterLinkForOrgParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetPilotMatterLinkForOrg(ctx context.Context, arg GetPilotMatterLinkForOrgParams) (PilotMatterLink, error) {
	row := q.db.QueryRow(ctx, getPilotMatterLinkForOrg, arg.ID, arg.OrganizationID)
	var i PilotMatterLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.CaseID,
		&i.CustomerReference,
		&i.CustomerStatus,
		&i.SubmittedAt,
		&i.LastCustomerViewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPilotMetrics = `-- name: GetPilotMetrics :one
SELECT
    COUNT(*)::int AS submitted_count,
    COUNT(CASE WHEN ml.customer_status = 'resolved' THEN 1 END)::int AS resolved_count,
    COUNT(CASE WHEN ml.customer_status = 'reopened' THEN 1 END)::int AS reopened_count,
    COUNT(CASE WHEN ml.customer_status = 'in_review' THEN 1 END)::int AS in_review_count,
    COUNT(CASE WHEN c.status = 'closed_unresolved' THEN 1 END)::int AS unresolved_count,
    COALESCE(EXTRACT(EPOCH FROM AVG(c.resolved_at - ml.submitted_at))::int, 0)::int AS avg_seconds_to_resolve,
    COALESCE(EXTRACT(EPOCH FROM (NOW() - MIN(CASE WHEN ml.customer_status = 'in_review' THEN ml.submitted_at END)))::int, 0)::int AS oldest_in_review_seconds,
    COUNT(CASE WHEN d.decision_source = 'accepted_proposal' THEN 1 END)::int AS accepted_proposal_count,
    COUNT(CASE WHEN d.decision_source = 'manual_override' THEN 1 END)::int AS manual_override_count
FROM pilot.matter_links ml
JOIN ops.case_records c ON c.id = ml.case_id
LEFT JOIN ops.case_decisions d ON d.case_id = c.id AND d.status = 'current'
`

type GetPilotMetricsRow struct {
	SubmittedCount        int32 `json:"submitted_count"`
	ResolvedCount         int32 `json:"resolved_count"`
	ReopenedCount         int32 `json:"reopened_count"`
	InReviewCount         int32 `json:"in_review_count"`
	UnresolvedCount       int32 `json:"unresolved_count"`
	AvgSecondsToResolve   int32 `json:"avg_seconds_to_resolve"`
	OldestInReviewSeconds int32 `json:"oldest_in_review_seconds"`
	AcceptedProposalCount int32 `json:"accepted_proposal_count"`
	ManualOverrideCount   int32 `json:"manual_override_count"`
}

func (q *Queries) GetPilotMetrics(ctx context.Context) (GetPilotMetricsRow, error) {
	row := q.db.QueryRow(ctx, getPilotMetrics)
	var i GetPilotMetricsRow
	err := row.Scan(
		&i.SubmittedCount,
		&i.ResolvedCount,
		&i.ReopenedCount,
		&i.InReviewCount,
		&i.UnresolvedCount,
		&i.AvgSecondsToResolve,
		&i.OldestInReviewSeconds,
		&i.AcceptedProposalCount,
		&i.ManualOverrideCount,
	)
	return i, err
}

const getPilotUserByEmail = `-- name: GetPilotUserByEmail :one
SELECT u.id, u.organization_id, u.email, u.display_name, u.role, u.password_hash, u.active, u.created_at,
       o.name AS organization_name, o.slug AS organization_slug, o.status AS organization_status
FROM pilot.users u
JOIN pilot.organizations o ON o.id = u.organization_id
WHERE lower(u.email) = lower($1)
`

type GetPilotUserByEmailRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	Email              string             `json:"email"`
	DisplayName        string             `json:"display_name"`
	Role               string             `json:"role"`
	PasswordHash       string             `json:"password_hash"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrganizationName   string             `json:"organization_name"`
	OrganizationSlug   string             `json:"organization_slug"`
	OrganizationStatus string             `json:"organization_status"`
}

func (q *Queries) GetPilotUserByEmail(ctx context.Context, lower string) (GetPilotUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPilotUserByEmail, lower)
	var i GetPilotUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.OrganizationName,
		&i.OrganizationSlug,
		&i.OrganizationStatus,
	)
	return i, err
}

const getPilotUserBySessionTokenHash = `-- name: GetPilotUserBySessionTokenHash :one
SELECT u.id, u.organization_id, u.email, u.display_name, u.role, u.password_hash, u.active, u.created_at,
       o.name AS organization_name, o.slug AS organization_slug, o.status AS organization_status
FROM pilot.sessions s
JOIN pilot.users u ON u.id = s.user_id
JOIN pilot.organizations o ON o.id = u.organization_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > NOW()
`

type GetPilotUserBySessionTokenHashRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	Email              string             `json:"email"`
	DisplayName        string             `json:"display_name"`
	Role               string             `json:"role"`
	PasswordHash       string             `json:"password_hash"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrganizationName   string             `json:"organization_name"`
	OrganizationSlug   string             `json:"organization_slug"`
	OrganizationStatus string             `json:"organization_status"`
}

func (q *Queries) GetPilotUserBySessionTokenHash(ctx context.Context, tokenHash string) (GetPilotUserBySessionTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getPilotUserBySessionTokenHash, tokenHash)
	var i GetPilotUserBySessionTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.CreatedAt,
		&i.OrganizationName,
		&i.OrganizationSlug,
		&i.OrganizationStatus,
	)
	return i, err
}

const listPilotMatterSummaries = `-- name: ListPilotMatterSummaries :many
SELECT ml.id AS matter_id,
       ml.case_id,
       ml.customer_reference,
       ml.customer_status,
       ml.submitted_at,
       ml.updated_at,
       c.case_reference,
       c.property_description,
       c.locality_or_area,
       c.municipality_or_deeds_office,
       c.title_reference,
       c.status AS internal_status,
       d.decision AS current_decision
FROM pilot.matter_links ml
JOIN ops.case_records c ON c.id = ml.case_id
LEFT JOIN ops.case_decisions d ON d.case_id = c.id AND d.status = 'current'
WHERE ml.organization_id = $1
  AND ($3::text IS NULL OR ml.customer_status = $3::text)
ORDER BY ml.submitted_at DESC
LIMIT $2
`

type ListPilotMatterSummariesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	CustomerStatus pgtype.Text `json:"customer_status"`
}

type ListPilotMatterSummariesRow struct {
	MatterID                  pgtype.UUID        `json:"matter_id"`
	CaseID                    pgtype.UUID        `json:"case_id"`
	CustomerReference         pgtype.Text        `json:"customer_reference"`
	CustomerStatus            string             `json:"customer_status"`
	SubmittedAt               pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	CaseReference             string             `json:"case_reference"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            pgtype.Text        `json:"title_reference"`
	InternalStatus            string             `json:"internal_status"`
	CurrentDecision           pgtype.Text        `json:"current_decision"`
}

func (q *Queries) ListPilotMatterSummaries(ctx context.Context, arg ListPilotMatterSummariesParams) ([]ListPilotMatterSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPilotMatterSummaries, arg.OrganizationID, arg.Limit, arg.CustomerStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPilotMatterSummariesRow
	for rows.Next() {
		var i ListPilotMatterSummariesRow
		if err := rows.Scan(
			&i.MatterID,
			&i.CaseID,
			&i.CustomerReference,
			&i.CustomerStatus,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.CaseReference,
			&i.PropertyDescription,
			&i.LocalityOrArea,
			&i.MunicipalityOrDeedsOffice,
			&i.TitleReference,
			&i.InternalStatus,
			&i.CurrentDecision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePilotSession = `-- name: RevokePilotSession :exec
UPDATE pilot.sessions
SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokePilotSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokePilotSession, tokenHash)
	return err
}

const touchPilotMatterViewed = `-- name: TouchPilotMatterViewed :exec
UPDATE pilot.matter_links
SET last_customer_viewed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND organization_id = $2
`

type TouchPilotMatterViewedParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) TouchPilotMatterViewed(ctx context.Context, arg TouchPilotMatterViewedParams) error {
	_, err := q.db.Exec(ctx, touchPilotMatterViewed, arg.ID, arg.OrganizationID)
	return err
}

const updatePilotMatterStatusByCase = `-- name: UpdatePilotMatterStatusByCase :exec
UPDATE pilot.matter_links
SET customer_status = $2, updated_at = NOW()
WHERE case_id = $1
`

type UpdatePilotMatterStatusByCaseParams struct {
	CaseID         pgtype.UUID `json:"case_id"`
	CustomerStatus string      `json:"customer_status"`
}

func (q *Queries) UpdatePilotMatterStatusByCase(ctx context.Context, arg UpdatePilotMatterStatusByCaseParams) error {
	_, err := q.db.Exec(ctx, updatePilotMatterStatusByCase, arg.CaseID, arg.CustomerStatus)
	return err
}
