// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPropertySummary = `-- name: GetPropertySummary :one
SELECT property_id, property_description, locality_or_area, municipality_or_deeds_office, title_reference, current_owner_name, status, updated_at
FROM read.property_summaries
WHERE property_id = $1
`

type GetPropertySummaryRow struct {
	PropertyID                pgtype.UUID        `json:"property_id"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            string             `json:"title_reference"`
	CurrentOwnerName          pgtype.Text        `json:"current_owner_name"`
	Status                    string             `json:"status"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPropertySummary(ctx context.Context, propertyID pgtype.UUID) (GetPropertySummaryRow, error) {
	row := q.db.QueryRow(ctx, getPropertySummary, propertyID)
	var i GetPropertySummaryRow
	err := row.Scan(
		&i.PropertyID,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.CurrentOwnerName,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const listPropertySummaries = `-- name: ListPropertySummaries :many
SELECT property_id, property_description, locality_or_area, municipality_or_deeds_office,
       title_reference, current_owner_name, status, updated_at
FROM read.property_summaries
WHERE ($1::text IS NULL
        OR lower(property_description) LIKE '%' || lower($1::text) || '%'
        OR lower(title_reference) LIKE '%' || lower($1::text) || '%')
  AND ($2::text IS NULL OR lower(locality_or_area) = lower($2::text))
  AND ($3::text IS NULL OR lower(status) = lower($3::text))
ORDER BY updated_at DESC
LIMIT $4
`

type ListPropertySummariesParams struct {
	Query    pgtype.Text `json:"query"`
	Locality pgtype.Text `json:"locality"`
	Status   pgtype.Text `json:"status"`
	Limit    int32       `json:"limit"`
}

type ListPropertySummariesRow struct {
	PropertyID                pgtype.UUID        `json:"property_id"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            string             `json:"title_reference"`
	CurrentOwnerName          pgtype.Text        `json:"current_owner_name"`
	Status                    string             `json:"status"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPropertySummaries(ctx context.Context, arg ListPropertySummariesParams) ([]ListPropertySummariesRow, error) {
	rows, err := q.db.Query(ctx, listPropertySummaries,
		arg.Query,
		arg.Locality,
		arg.Status,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPropertySummariesRow
	for rows.Next() {
		var i ListPropertySummariesRow
		if err := rows.Scan(
			&i.PropertyID,
			&i.PropertyDescription,
			&i.LocalityOrArea,
			&i.MunicipalityOrDeedsOffice,
			&i.TitleReference,
			&i.CurrentOwnerName,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshPropertySummaryFromCore = `-- name: RefreshPropertySummaryFromCore :exec
INSERT INTO read.property_summaries (
    property_id, property_description, locality_or_area,
    municipality_or_deeds_office, title_reference,
    current_owner_name, status, updated_at
)
SELECT p.id,
       p.property_description,
       p.municipality_or_deeds_office,
       p.municipality_or_deeds_office,
       p.latest_title_reference,
       MAX(pp.party_name) FILTER (WHERE pp.party_role = 'owner'),
       COALESCE(MAX(e.status) FILTER (WHERE e.status != ''), 'normalized'),
       NOW()
FROM core.properties p
LEFT JOIN core.property_parties pp ON pp.property_id = p.id
LEFT JOIN core.encumbrances e ON e.property_id = p.id
WHERE p.id = $1
GROUP BY p.id, p.property_description, p.municipality_or_deeds_office, p.latest_title_reference
ON CONFLICT (property_id) DO UPDATE
SET property_description = EXCLUDED.property_description,
    locality_or_area = EXCLUDED.locality_or_area,
    municipality_or_deeds_office = EXCLUDED.municipality_or_deeds_office,
    title_reference = EXCLUDED.title_reference,
    current_owner_name = EXCLUDED.current_owner_name,
    status = EXCLUDED.status,
    updated_at = NOW()
`

// locality_or_area falls back to municipality_or_deeds_office since core.properties does not have a separate locality column
func (q *Queries) RefreshPropertySummaryFromCore(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshPropertySummaryFromCore, id)
	return err
}

const upsertCoreProperty = `-- name: UpsertCoreProperty :one
INSERT INTO core.properties (property_fingerprint, municipality_or_deeds_office, property_description, latest_title_reference)
VALUES ($1, $2, $3, $4)
ON CONFLICT (property_fingerprint) DO UPDATE
SET municipality_or_deeds_office = EXCLUDED.municipality_or_deeds_office,
    property_description = EXCLUDED.property_description,
    latest_title_reference = EXCLUDED.latest_title_reference,
    updated_at = NOW()
RETURNING id, property_fingerprint, municipality_or_deeds_office, property_description, latest_title_reference, created_at, updated_at
`

type UpsertCorePropertyParams struct {
	PropertyFingerprint       string `json:"property_fingerprint"`
	MunicipalityOrDeedsOffice string `json:"municipality_or_deeds_office"`
	PropertyDescription       string `json:"property_description"`
	LatestTitleReference      string `json:"latest_title_reference"`
}

func (q *Queries) UpsertCoreProperty(ctx context.Context, arg UpsertCorePropertyParams) (CoreProperty, error) {
	row := q.db.QueryRow(ctx, upsertCoreProperty,
		arg.PropertyFingerprint,
		arg.MunicipalityOrDeedsOffice,
		arg.PropertyDescription,
		arg.LatestTitleReference,
	)
	var i CoreProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyFingerprint,
		&i.MunicipalityOrDeedsOffice,
		&i.PropertyDescription,
		&i.LatestTitleReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPropertySummary = `-- name: UpsertPropertySummary :exec
INSERT INTO read.property_summaries (
    property_id, property_description, locality_or_area,
    municipality_or_deeds_office, title_reference,
    current_owner_name, status, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
) ON CONFLICT (property_id) DO UPDATE SET
    property_description = EXCLUDED.property_description,
    locality_or_area = EXCLUDED.locality_or_area,
    municipality_or_deeds_office = EXCLUDED.municipality_or_deeds_office,
    title_reference = EXCLUDED.title_reference,
    current_owner_name = EXCLUDED.current_owner_name,
    status = EXCLUDED.status,
    updated_at = NOW()
`

type UpsertPropertySummaryParams struct {
	PropertyID                pgtype.UUID `json:"property_id"`
	PropertyDescription       string      `json:"property_description"`
	LocalityOrArea            string      `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string      `json:"municipality_or_deeds_office"`
	TitleReference            string      `json:"title_reference"`
	CurrentOwnerName          pgtype.Text `json:"current_owner_name"`
	Status                    string      `json:"status"`
}

func (q *Queries) UpsertPropertySummary(ctx context.Context, arg UpsertPropertySummaryParams) error {
	_, err := q.db.Exec(ctx, upsertPropertySummary,
		arg.PropertyID,
		arg.PropertyDescription,
		arg.LocalityOrArea,
		arg.MunicipalityOrDeedsOffice,
		arg.TitleReference,
		arg.CurrentOwnerName,
		arg.Status,
	)
	return err
}
