// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPropertySummaryCandidates = `-- name: FindPropertySummaryCandidates :many
WITH submitted AS (
    SELECT
        NULLIF(BTRIM($1::text), '') AS title_reference,
        NULLIF(BTRIM($2::text), '') AS property_description,
        NULLIF(BTRIM($3::text), '') AS locality_or_area,
        NULLIF(BTRIM($4::text), '') AS municipality_or_deeds_office
),
scored AS (
    SELECT
        ps.property_id,
        ps.property_description,
        ps.locality_or_area,
        ps.municipality_or_deeds_office,
        ps.title_reference,
        ps.current_owner_name,
        ps.status,
        ps.updated_at,
        CASE
            WHEN submitted.title_reference IS NOT NULL
                AND LOWER(BTRIM(ps.title_reference)) = LOWER(submitted.title_reference)
                THEN 100
            WHEN submitted.property_description IS NOT NULL
                AND NULLIF(BTRIM(ps.property_description), '') IS NOT NULL
                AND LOWER(BTRIM(ps.property_description)) = LOWER(submitted.property_description)
                AND (
                    submitted.locality_or_area IS NULL
                    OR NULLIF(BTRIM(ps.locality_or_area), '') IS NULL
                    OR LOWER(BTRIM(ps.locality_or_area)) = LOWER(submitted.locality_or_area)
                )
                AND (
                    submitted.municipality_or_deeds_office IS NULL
                    OR NULLIF(BTRIM(ps.municipality_or_deeds_office), '') IS NULL
                    OR LOWER(BTRIM(ps.municipality_or_deeds_office)) = LOWER(submitted.municipality_or_deeds_office)
                )
                THEN 85
            WHEN submitted.property_description IS NOT NULL
                AND NULLIF(BTRIM(ps.property_description), '') IS NOT NULL
                AND (
                    LOWER(ps.property_description) LIKE '%' || LOWER(submitted.property_description) || '%'
                    OR LOWER(submitted.property_description) LIKE '%' || LOWER(ps.property_description) || '%'
                )
                AND (
                    submitted.locality_or_area IS NULL
                    OR NULLIF(BTRIM(ps.locality_or_area), '') IS NULL
                    OR LOWER(BTRIM(ps.locality_or_area)) = LOWER(submitted.locality_or_area)
                )
                AND (
                    submitted.municipality_or_deeds_office IS NULL
                    OR NULLIF(BTRIM(ps.municipality_or_deeds_office), '') IS NULL
                    OR LOWER(BTRIM(ps.municipality_or_deeds_office)) = LOWER(submitted.municipality_or_deeds_office)
                )
                THEN 70
            WHEN submitted.locality_or_area IS NOT NULL
                AND submitted.municipality_or_deeds_office IS NOT NULL
                AND LOWER(BTRIM(ps.locality_or_area)) = LOWER(submitted.locality_or_area)
                AND LOWER(BTRIM(ps.municipality_or_deeds_office)) = LOWER(submitted.municipality_or_deeds_office)
                THEN 60
            WHEN submitted.locality_or_area IS NOT NULL
                AND LOWER(BTRIM(ps.locality_or_area)) = LOWER(submitted.locality_or_area)
                THEN 55
            WHEN submitted.municipality_or_deeds_office IS NOT NULL
                AND LOWER(BTRIM(ps.municipality_or_deeds_office)) = LOWER(submitted.municipality_or_deeds_office)
                THEN 50
            ELSE 0
        END::int AS confidence_score,
        COUNT(sl.id)::int AS source_provenance_count
    FROM read.property_summaries ps
    CROSS JOIN submitted
    LEFT JOIN core.source_links sl ON sl.property_id = ps.property_id
    WHERE (
        submitted.title_reference IS NOT NULL
            AND LOWER(BTRIM(ps.title_reference)) = LOWER(submitted.title_reference)
    ) OR (
        submitted.property_description IS NOT NULL
            AND NULLIF(BTRIM(ps.property_description), '') IS NOT NULL
            AND LOWER(BTRIM(ps.property_description)) = LOWER(submitted.property_description)
            AND (
                submitted.locality_or_area IS NULL
                OR NULLIF(BTRIM(ps.locality_or_area), '') IS NULL
                OR LOWER(BTRIM(ps.locality_or_area)) = LOWER(submitted.locality_or_area)
            )
            AND (
                submitted.municipality_or_deeds_office IS NULL
                OR NULLIF(BTRIM(ps.municipality_or_deeds_office), '') IS NULL
                OR LOWER(BTRIM(ps.municipality_or_deeds_office)) = LOWER(submitted.municipality_or_deeds_office)
            )
    ) OR (
        submitted.property_description IS NOT NULL
            AND NULLIF(BTRIM(ps.property_description), '') IS NOT NULL
            AND (
                LOWER(ps.property_description) LIKE '%' || LOWER(submitted.property_description) || '%'
                OR LOWER(submitted.property_description) LIKE '%' || LOWER(ps.property_description) || '%'
            )
            AND (
                submitted.locality_or_area IS NULL
                OR NULLIF(BTRIM(ps.locality_or_area), '') IS NULL
                OR LOWER(BTRIM(ps.locality_or_area)) = LOWER(submitted.locality_or_area)
            )
            AND (
                submitted.municipality_or_deeds_office IS NULL
                OR NULLIF(BTRIM(ps.municipality_or_deeds_office), '') IS NULL
                OR LOWER(BTRIM(ps.municipality_or_deeds_office)) = LOWER(submitted.municipality_or_deeds_office)
            )
    ) OR (
        submitted.locality_or_area IS NOT NULL
            AND LOWER(BTRIM(ps.locality_or_area)) = LOWER(submitted.locality_or_area)
    ) OR (
        submitted.municipality_or_deeds_office IS NOT NULL
            AND LOWER(BTRIM(ps.municipality_or_deeds_office)) = LOWER(submitted.municipality_or_deeds_office)
    )
    GROUP BY ps.property_id, ps.property_description, ps.locality_or_area,
             ps.municipality_or_deeds_office, ps.title_reference,
             ps.current_owner_name, ps.status, ps.updated_at,
             submitted.title_reference, submitted.property_description,
             submitted.locality_or_area, submitted.municipality_or_deeds_office
)
SELECT property_id, property_description, locality_or_area, municipality_or_deeds_office,
       title_reference, current_owner_name, status, updated_at,
       confidence_score, source_provenance_count
FROM scored
WHERE confidence_score > 0
ORDER BY confidence_score DESC, source_provenance_count DESC, updated_at DESC, property_id
LIMIT 5
`

type FindPropertySummaryCandidatesParams struct {
	TitleReference            string `json:"title_reference"`
	PropertyDescription       string `json:"property_description"`
	LocalityOrArea            string `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string `json:"municipality_or_deeds_office"`
}

type FindPropertySummaryCandidatesRow struct {
	PropertyID                pgtype.UUID        `json:"property_id"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            string             `json:"title_reference"`
	CurrentOwnerName          pgtype.Text        `json:"current_owner_name"`
	Status                    string             `json:"status"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	ConfidenceScore           int32              `json:"confidence_score"`
	SourceProvenanceCount     int32              `json:"source_provenance_count"`
}

func (q *Queries) FindPropertySummaryCandidates(ctx context.Context, arg FindPropertySummaryCandidatesParams) ([]FindPropertySummaryCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findPropertySummaryCandidates,
		arg.TitleReference,
		arg.PropertyDescription,
		arg.LocalityOrArea,
		arg.MunicipalityOrDeedsOffice,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPropertySummaryCandidatesRow
	for rows.Next() {
		var i FindPropertySummaryCandidatesRow
		if err := rows.Scan(
			&i.PropertyID,
			&i.PropertyDescription,
			&i.LocalityOrArea,
			&i.MunicipalityOrDeedsOffice,
			&i.TitleReference,
			&i.CurrentOwnerName,
			&i.Status,
			&i.UpdatedAt,
			&i.ConfidenceScore,
			&i.SourceProvenanceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertySummary = `-- name: GetPropertySummary :one
SELECT property_id, property_description, locality_or_area, municipality_or_deeds_office, title_reference, current_owner_name, status, updated_at
FROM read.property_summaries
WHERE property_id = $1
`

type GetPropertySummaryRow struct {
	PropertyID                pgtype.UUID        `json:"property_id"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            string             `json:"title_reference"`
	CurrentOwnerName          pgtype.Text        `json:"current_owner_name"`
	Status                    string             `json:"status"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPropertySummary(ctx context.Context, propertyID pgtype.UUID) (GetPropertySummaryRow, error) {
	row := q.db.QueryRow(ctx, getPropertySummary, propertyID)
	var i GetPropertySummaryRow
	err := row.Scan(
		&i.PropertyID,
		&i.PropertyDescription,
		&i.LocalityOrArea,
		&i.MunicipalityOrDeedsOffice,
		&i.TitleReference,
		&i.CurrentOwnerName,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoreSourceLinksByProperty = `-- name: ListCoreSourceLinksByProperty :many
SELECT id, property_id, batch_id, source_record_id, fact_table, fact_id, created_at
FROM core.source_links
WHERE property_id = $1
ORDER BY created_at, fact_table, fact_id
`

func (q *Queries) ListCoreSourceLinksByProperty(ctx context.Context, propertyID pgtype.UUID) ([]CoreSourceLink, error) {
	rows, err := q.db.Query(ctx, listCoreSourceLinksByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreSourceLink
	for rows.Next() {
		var i CoreSourceLink
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.BatchID,
			&i.SourceRecordID,
			&i.FactTable,
			&i.FactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertySummaries = `-- name: ListPropertySummaries :many
SELECT property_id, property_description, locality_or_area, municipality_or_deeds_office,
       title_reference, current_owner_name, status, updated_at
FROM read.property_summaries
WHERE ($1::text IS NULL
        OR lower(property_description) LIKE '%' || lower($1::text) || '%'
        OR lower(title_reference) LIKE '%' || lower($1::text) || '%')
  AND ($2::text IS NULL OR lower(locality_or_area) = lower($2::text))
  AND ($3::text IS NULL OR lower(status) = lower($3::text))
ORDER BY updated_at DESC
LIMIT $4
`

type ListPropertySummariesParams struct {
	Query    pgtype.Text `json:"query"`
	Locality pgtype.Text `json:"locality"`
	Status   pgtype.Text `json:"status"`
	Limit    int32       `json:"limit"`
}

type ListPropertySummariesRow struct {
	PropertyID                pgtype.UUID        `json:"property_id"`
	PropertyDescription       string             `json:"property_description"`
	LocalityOrArea            string             `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string             `json:"municipality_or_deeds_office"`
	TitleReference            string             `json:"title_reference"`
	CurrentOwnerName          pgtype.Text        `json:"current_owner_name"`
	Status                    string             `json:"status"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPropertySummaries(ctx context.Context, arg ListPropertySummariesParams) ([]ListPropertySummariesRow, error) {
	rows, err := q.db.Query(ctx, listPropertySummaries,
		arg.Query,
		arg.Locality,
		arg.Status,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPropertySummariesRow
	for rows.Next() {
		var i ListPropertySummariesRow
		if err := rows.Scan(
			&i.PropertyID,
			&i.PropertyDescription,
			&i.LocalityOrArea,
			&i.MunicipalityOrDeedsOffice,
			&i.TitleReference,
			&i.CurrentOwnerName,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshPropertySummaryFromCore = `-- name: RefreshPropertySummaryFromCore :exec
INSERT INTO read.property_summaries (
    property_id, property_description, locality_or_area,
    municipality_or_deeds_office, title_reference,
    current_owner_name, status, updated_at
)
SELECT p.id,
       p.property_description,
       p.municipality_or_deeds_office,
       p.municipality_or_deeds_office,
       p.latest_title_reference,
       MAX(pp.party_name) FILTER (WHERE pp.party_role = 'owner'),
       COALESCE(MAX(e.status) FILTER (WHERE e.status != ''), 'normalized'),
       NOW()
FROM core.properties p
LEFT JOIN core.property_parties pp ON pp.property_id = p.id
LEFT JOIN core.encumbrances e ON e.property_id = p.id
WHERE p.id = $1
GROUP BY p.id, p.property_description, p.municipality_or_deeds_office, p.latest_title_reference
ON CONFLICT (property_id) DO UPDATE
SET property_description = EXCLUDED.property_description,
    locality_or_area = EXCLUDED.locality_or_area,
    municipality_or_deeds_office = EXCLUDED.municipality_or_deeds_office,
    title_reference = EXCLUDED.title_reference,
    current_owner_name = EXCLUDED.current_owner_name,
    status = EXCLUDED.status,
    updated_at = NOW()
`

// locality_or_area falls back to municipality_or_deeds_office since core.properties does not have a separate locality column
func (q *Queries) RefreshPropertySummaryFromCore(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshPropertySummaryFromCore, id)
	return err
}

const upsertCoreProperty = `-- name: UpsertCoreProperty :one
INSERT INTO core.properties (property_fingerprint, municipality_or_deeds_office, property_description, latest_title_reference)
VALUES ($1, $2, $3, $4)
ON CONFLICT (property_fingerprint) DO UPDATE
SET municipality_or_deeds_office = EXCLUDED.municipality_or_deeds_office,
    property_description = EXCLUDED.property_description,
    latest_title_reference = EXCLUDED.latest_title_reference,
    updated_at = NOW()
RETURNING id, property_fingerprint, municipality_or_deeds_office, property_description, latest_title_reference, created_at, updated_at
`

type UpsertCorePropertyParams struct {
	PropertyFingerprint       string `json:"property_fingerprint"`
	MunicipalityOrDeedsOffice string `json:"municipality_or_deeds_office"`
	PropertyDescription       string `json:"property_description"`
	LatestTitleReference      string `json:"latest_title_reference"`
}

func (q *Queries) UpsertCoreProperty(ctx context.Context, arg UpsertCorePropertyParams) (CoreProperty, error) {
	row := q.db.QueryRow(ctx, upsertCoreProperty,
		arg.PropertyFingerprint,
		arg.MunicipalityOrDeedsOffice,
		arg.PropertyDescription,
		arg.LatestTitleReference,
	)
	var i CoreProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyFingerprint,
		&i.MunicipalityOrDeedsOffice,
		&i.PropertyDescription,
		&i.LatestTitleReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPropertySummary = `-- name: UpsertPropertySummary :exec
INSERT INTO read.property_summaries (
    property_id, property_description, locality_or_area,
    municipality_or_deeds_office, title_reference,
    current_owner_name, status, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
) ON CONFLICT (property_id) DO UPDATE SET
    property_description = EXCLUDED.property_description,
    locality_or_area = EXCLUDED.locality_or_area,
    municipality_or_deeds_office = EXCLUDED.municipality_or_deeds_office,
    title_reference = EXCLUDED.title_reference,
    current_owner_name = EXCLUDED.current_owner_name,
    status = EXCLUDED.status,
    updated_at = NOW()
`

type UpsertPropertySummaryParams struct {
	PropertyID                pgtype.UUID `json:"property_id"`
	PropertyDescription       string      `json:"property_description"`
	LocalityOrArea            string      `json:"locality_or_area"`
	MunicipalityOrDeedsOffice string      `json:"municipality_or_deeds_office"`
	TitleReference            string      `json:"title_reference"`
	CurrentOwnerName          pgtype.Text `json:"current_owner_name"`
	Status                    string      `json:"status"`
}

func (q *Queries) UpsertPropertySummary(ctx context.Context, arg UpsertPropertySummaryParams) error {
	_, err := q.db.Exec(ctx, upsertPropertySummary,
		arg.PropertyID,
		arg.PropertyDescription,
		arg.LocalityOrArea,
		arg.MunicipalityOrDeedsOffice,
		arg.TitleReference,
		arg.CurrentOwnerName,
		arg.Status,
	)
	return err
}
