// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ClaimNextJob(ctx context.Context, arg ClaimNextJobParams) (OpsJob, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (OpsRun, error)
	ListRuns(ctx context.Context, limit int32) ([]OpsRun, error)
}

var _ Querier = (*Queries)(nil)
