// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCaseEvidence(ctx context.Context, arg AddCaseEvidenceParams) (OpsCaseEvidenceItem, error)
	AddCaseParty(ctx context.Context, arg AddCasePartyParams) (OpsCaseParty, error)
	AddDecisionProposalReasonCode(ctx context.Context, arg AddDecisionProposalReasonCodeParams) error
	AddDecisionReasonCode(ctx context.Context, arg AddDecisionReasonCodeParams) error
	ClaimNextJob(ctx context.Context, arg ClaimNextJobParams) (OpsJob, error)
	CloseCaseUnresolved(ctx context.Context, id pgtype.UUID) (CloseCaseUnresolvedRow, error)
	ConfirmCasePropertyMatch(ctx context.Context, arg ConfirmCasePropertyMatchParams) (OpsCasePropertyMatch, error)
	CreateAcceptedDecisionFromProposal(ctx context.Context, arg CreateAcceptedDecisionFromProposalParams) (OpsCaseDecision, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (RawBatch, error)
	CreateCaseAuditEvent(ctx context.Context, arg CreateCaseAuditEventParams) (OpsCaseAuditEvent, error)
	CreateCaseDecision(ctx context.Context, arg CreateCaseDecisionParams) (OpsCaseDecision, error)
	CreateCaseRecord(ctx context.Context, arg CreateCaseRecordParams) (CreateCaseRecordRow, error)
	CreateDecisionProposal(ctx context.Context, arg CreateDecisionProposalParams) (OpsCaseDecisionProposal, error)
	CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (OpsJob, error)
	CreateIngestionRun(ctx context.Context, batchID pgtype.UUID) (OpsRun, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (OpsJob, error)
	CreatePilotMatterLink(ctx context.Context, arg CreatePilotMatterLinkParams) (PilotMatterLink, error)
	CreatePilotSession(ctx context.Context, arg CreatePilotSessionParams) (PilotSession, error)
	CreatePilotSummaryExport(ctx context.Context, arg CreatePilotSummaryExportParams) (PilotSummaryExport, error)
	CreatePropertyMatch(ctx context.Context, arg CreatePropertyMatchParams) (OpsCasePropertyMatch, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (OpsRun, error)
	CreateSourceBatch(ctx context.Context, arg CreateSourceBatchParams) (RawBatch, error)
	FindActiveRun(ctx context.Context, runType string) (OpsRun, error)
	GetAnalyst(ctx context.Context, id string) (OpsAnalyst, error)
	GetCaseRecord(ctx context.Context, id pgtype.UUID) (GetCaseRecordRow, error)
	GetCurrentDecisionProposal(ctx context.Context, caseID pgtype.UUID) (OpsCaseDecisionProposal, error)
	GetDecisioningPropertySnapshot(ctx context.Context, id pgtype.UUID) (GetDecisioningPropertySnapshotRow, error)
	GetPilotCaseContext(ctx context.Context, caseID pgtype.UUID) (GetPilotCaseContextRow, error)
	GetPilotMatterLinkForOrg(ctx context.Context, arg GetPilotMatterLinkForOrgParams) (PilotMatterLink, error)
	GetPilotMetrics(ctx context.Context) (GetPilotMetricsRow, error)
	GetPilotUserByEmail(ctx context.Context, lower string) (GetPilotUserByEmailRow, error)
	GetPilotUserBySessionTokenHash(ctx context.Context, tokenHash string) (GetPilotUserBySessionTokenHashRow, error)
	GetPropertySummary(ctx context.Context, propertyID pgtype.UUID) (GetPropertySummaryRow, error)
	GetSeedProperty(ctx context.Context, id pgtype.UUID) (OpsSeedProperty, error)
	InsertRawRecord(ctx context.Context, arg InsertRawRecordParams) error
	LinkCaseSeedProperty(ctx context.Context, arg LinkCaseSeedPropertyParams) (LinkCaseSeedPropertyRow, error)
	ListAnalysts(ctx context.Context) ([]OpsAnalyst, error)
	ListCaseAuditEvents(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseAuditEvent, error)
	ListCaseDecisions(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseDecision, error)
	ListCaseEvidence(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseEvidenceItem, error)
	ListCaseParties(ctx context.Context, caseID pgtype.UUID) ([]OpsCaseParty, error)
	ListCasePropertyMatches(ctx context.Context, caseID pgtype.UUID) ([]OpsCasePropertyMatch, error)
	ListCaseSummaries(ctx context.Context, arg ListCaseSummariesParams) ([]ListCaseSummariesRow, error)
	ListCoreSourceLinksByProperty(ctx context.Context, propertyID pgtype.UUID) ([]CoreSourceLink, error)
	ListDecisionProposalReasonCodes(ctx context.Context, proposalID pgtype.UUID) ([]OpsReasonCode, error)
	ListDecisionReasonCodes(ctx context.Context, decisionID pgtype.UUID) ([]ListDecisionReasonCodesRow, error)
	ListDecisioningPropertyParties(ctx context.Context, propertyID pgtype.UUID) ([]ListDecisioningPropertyPartiesRow, error)
	ListPilotCaseContexts(ctx context.Context, organizationID pgtype.UUID) ([]ListPilotCaseContextsRow, error)
	ListPilotMatterSummaries(ctx context.Context, arg ListPilotMatterSummariesParams) ([]ListPilotMatterSummariesRow, error)
	ListPropertySummaries(ctx context.Context, arg ListPropertySummariesParams) ([]ListPropertySummariesRow, error)
	ListReasonCodes(ctx context.Context) ([]OpsReasonCode, error)
	ListRuns(ctx context.Context, limit int32) ([]OpsRun, error)
	ListRunsWithCounts(ctx context.Context, limit int32) ([]ListRunsWithCountsRow, error)
	ListSeedPropertyMatches(ctx context.Context, arg ListSeedPropertyMatchesParams) ([]OpsSeedProperty, error)
	ReassignCase(ctx context.Context, arg ReassignCaseParams) (ReassignCaseRow, error)
	// locality_or_area falls back to municipality_or_deeds_office since core.properties does not have a separate locality column
	RefreshPropertySummaryFromCore(ctx context.Context, id pgtype.UUID) error
	RejectCasePropertyMatches(ctx context.Context, caseID pgtype.UUID) error
	ReopenCase(ctx context.Context, id pgtype.UUID) (ReopenCaseRow, error)
	ResolveCase(ctx context.Context, id pgtype.UUID) (ResolveCaseRow, error)
	RevokePilotSession(ctx context.Context, tokenHash string) error
	SupersedeCurrentDecisionProposal(ctx context.Context, caseID pgtype.UUID) error
	SupersedeCurrentDecisions(ctx context.Context, caseID pgtype.UUID) error
	TouchPilotMatterViewed(ctx context.Context, arg TouchPilotMatterViewedParams) error
	UnblockNextJob(ctx context.Context, arg UnblockNextJobParams) error
	UpdatePilotMatterStatusByCase(ctx context.Context, arg UpdatePilotMatterStatusByCaseParams) error
	UpsertCoreProperty(ctx context.Context, arg UpsertCorePropertyParams) (CoreProperty, error)
	UpsertPropertySummary(ctx context.Context, arg UpsertPropertySummaryParams) error
}

var _ Querier = (*Queries)(nil)
