// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source_ingestion.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceBatch = `-- name: CreateSourceBatch :one
INSERT INTO raw.batches (source_name, source_batch_key, payload_uri, payload_sha256)
VALUES ($1, $2, $3, $4)
RETURNING id, source_name, source_batch_key, payload_uri, payload_sha256, imported_at, created_at
`

type CreateSourceBatchParams struct {
	SourceName     string      `json:"source_name"`
	SourceBatchKey string      `json:"source_batch_key"`
	PayloadUri     pgtype.Text `json:"payload_uri"`
	PayloadSha256  string      `json:"payload_sha256"`
}

func (q *Queries) CreateSourceBatch(ctx context.Context, arg CreateSourceBatchParams) (RawBatch, error) {
	row := q.db.QueryRow(ctx, createSourceBatch,
		arg.SourceName,
		arg.SourceBatchKey,
		arg.PayloadUri,
		arg.PayloadSha256,
	)
	var i RawBatch
	err := row.Scan(
		&i.ID,
		&i.SourceName,
		&i.SourceBatchKey,
		&i.PayloadUri,
		&i.PayloadSha256,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRawRecord = `-- name: InsertRawRecord :exec
INSERT INTO raw.records (batch_id, record_key, record_type, payload, payload_sha256)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (batch_id, record_key) DO NOTHING
`

type InsertRawRecordParams struct {
	BatchID       pgtype.UUID `json:"batch_id"`
	RecordKey     string      `json:"record_key"`
	RecordType    string      `json:"record_type"`
	Payload       []byte      `json:"payload"`
	PayloadSha256 string      `json:"payload_sha256"`
}

func (q *Queries) InsertRawRecord(ctx context.Context, arg InsertRawRecordParams) error {
	_, err := q.db.Exec(ctx, insertRawRecord,
		arg.BatchID,
		arg.RecordKey,
		arg.RecordType,
		arg.Payload,
		arg.PayloadSha256,
	)
	return err
}
